// Code generated by ent, DO NOT EDIT.

package usagestat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldID, id))
}

// BucketTime applies equality check predicate on the "bucket_time" field. It's identical to BucketTimeEQ.
func BucketTime(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldBucketTime, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldGroupID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldModel, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldRequestCount, v))
}

// ErrorCount applies equality check predicate on the "error_count" field. It's identical to ErrorCountEQ.
func ErrorCount(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldErrorCount, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldOutputTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTotalTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCost, v))
}

// RawCost applies equality check predicate on the "raw_cost" field. It's identical to RawCostEQ.
func RawCost(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldRawCost, v))
}

// CallCount applies equality check predicate on the "call_count" field. It's identical to CallCountEQ.
func CallCount(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCallCount, v))
}

// TtftTotalMs applies equality check predicate on the "ttft_total_ms" field. It's identical to TtftTotalMsEQ.
func TtftTotalMs(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTtftTotalMs, v))
}

// TtftCount applies equality check predicate on the "ttft_count" field. It's identical to TtftCountEQ.
func TtftCount(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTtftCount, v))
}

// TtftMaxMs applies equality check predicate on the "ttft_max_ms" field. It's identical to TtftMaxMsEQ.
func TtftMaxMs(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTtftMaxMs, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldUpdatedAt, v))
}

// BucketTimeEQ applies the EQ predicate on the "bucket_time" field.
func BucketTimeEQ(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldBucketTime, v))
}

// BucketTimeNEQ applies the NEQ predicate on the "bucket_time" field.
func BucketTimeNEQ(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldBucketTime, v))
}

// BucketTimeIn applies the In predicate on the "bucket_time" field.
func BucketTimeIn(vs ...time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldBucketTime, vs...))
}

// BucketTimeNotIn applies the NotIn predicate on the "bucket_time" field.
func BucketTimeNotIn(vs ...time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldBucketTime, vs...))
}

// BucketTimeGT applies the GT predicate on the "bucket_time" field.
func BucketTimeGT(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldBucketTime, v))
}

// BucketTimeGTE applies the GTE predicate on the "bucket_time" field.
func BucketTimeGTE(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldBucketTime, v))
}

// BucketTimeLT applies the LT predicate on the "bucket_time" field.
func BucketTimeLT(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldBucketTime, v))
}

// BucketTimeLTE applies the LTE predicate on the "bucket_time" field.
func BucketTimeLTE(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldBucketTime, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldGroupID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldContainsFold(FieldModel, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldRequestCount, v))
}

// ErrorCountEQ applies the EQ predicate on the "error_count" field.
func ErrorCountEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldErrorCount, v))
}

// ErrorCountNEQ applies the NEQ predicate on the "error_count" field.
func ErrorCountNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldErrorCount, v))
}

// ErrorCountIn applies the In predicate on the "error_count" field.
func ErrorCountIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldErrorCount, vs...))
}

// ErrorCountNotIn applies the NotIn predicate on the "error_count" field.
func ErrorCountNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldErrorCount, vs...))
}

// ErrorCountGT applies the GT predicate on the "error_count" field.
func ErrorCountGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldErrorCount, v))
}

// ErrorCountGTE applies the GTE predicate on the "error_count" field.
func ErrorCountGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldErrorCount, v))
}

// ErrorCountLT applies the LT predicate on the "error_count" field.
func ErrorCountLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldErrorCount, v))
}

// ErrorCountLTE applies the LTE predicate on the "error_count" field.
func ErrorCountLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldErrorCount, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldOutputTokens, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldTotalTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldCacheReadTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldCost, v))
}

// RawCostEQ applies the EQ predicate on the "raw_cost" field.
func RawCostEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldRawCost, v))
}

// RawCostNEQ applies the NEQ predicate on the "raw_cost" field.
func RawCostNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldRawCost, v))
}

// RawCostIn applies the In predicate on the "raw_cost" field.
func RawCostIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldRawCost, vs...))
}

// RawCostNotIn applies the NotIn predicate on the "raw_cost" field.
func RawCostNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldRawCost, vs...))
}

// RawCostGT applies the GT predicate on the "raw_cost" field.
func RawCostGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldRawCost, v))
}

// RawCostGTE applies the GTE predicate on the "raw_cost" field.
func RawCostGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldRawCost, v))
}

// RawCostLT applies the LT predicate on the "raw_cost" field.
func RawCostLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldRawCost, v))
}

// RawCostLTE applies the LTE predicate on the "raw_cost" field.
func RawCostLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldRawCost, v))
}

// CallCountEQ applies the EQ predicate on the "call_count" field.
func CallCountEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldCallCount, v))
}

// CallCountNEQ applies the NEQ predicate on the "call_count" field.
func CallCountNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldCallCount, v))
}

// CallCountIn applies the In predicate on the "call_count" field.
func CallCountIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldCallCount, vs...))
}

// CallCountNotIn applies the NotIn predicate on the "call_count" field.
func CallCountNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldCallCount, vs...))
}

// CallCountGT applies the GT predicate on the "call_count" field.
func CallCountGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldCallCount, v))
}

// CallCountGTE applies the GTE predicate on the "call_count" field.
func CallCountGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldCallCount, v))
}

// CallCountLT applies the LT predicate on the "call_count" field.
func CallCountLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldCallCount, v))
}

// CallCountLTE applies the LTE predicate on the "call_count" field.
func CallCountLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldCallCount, v))
}

// TtftTotalMsEQ applies the EQ predicate on the "ttft_total_ms" field.
func TtftTotalMsEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTtftTotalMs, v))
}

// TtftTotalMsNEQ applies the NEQ predicate on the "ttft_total_ms" field.
func TtftTotalMsNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldTtftTotalMs, v))
}

// TtftTotalMsIn applies the In predicate on the "ttft_total_ms" field.
func TtftTotalMsIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldTtftTotalMs, vs...))
}

// TtftTotalMsNotIn applies the NotIn predicate on the "ttft_total_ms" field.
func TtftTotalMsNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldTtftTotalMs, vs...))
}

// TtftTotalMsGT applies the GT predicate on the "ttft_total_ms" field.
func TtftTotalMsGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldTtftTotalMs, v))
}

// TtftTotalMsGTE applies the GTE predicate on the "ttft_total_ms" field.
func TtftTotalMsGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldTtftTotalMs, v))
}

// TtftTotalMsLT applies the LT predicate on the "ttft_total_ms" field.
func TtftTotalMsLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldTtftTotalMs, v))
}

// TtftTotalMsLTE applies the LTE predicate on the "ttft_total_ms" field.
func TtftTotalMsLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldTtftTotalMs, v))
}

// TtftCountEQ applies the EQ predicate on the "ttft_count" field.
func TtftCountEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTtftCount, v))
}

// TtftCountNEQ applies the NEQ predicate on the "ttft_count" field.
func TtftCountNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldTtftCount, v))
}

// TtftCountIn applies the In predicate on the "ttft_count" field.
func TtftCountIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldTtftCount, vs...))
}

// TtftCountNotIn applies the NotIn predicate on the "ttft_count" field.
func TtftCountNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldTtftCount, vs...))
}

// TtftCountGT applies the GT predicate on the "ttft_count" field.
func TtftCountGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldTtftCount, v))
}

// TtftCountGTE applies the GTE predicate on the "ttft_count" field.
func TtftCountGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldTtftCount, v))
}

// TtftCountLT applies the LT predicate on the "ttft_count" field.
func TtftCountLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldTtftCount, v))
}

// TtftCountLTE applies the LTE predicate on the "ttft_count" field.
func TtftCountLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldTtftCount, v))
}

// TtftMaxMsEQ applies the EQ predicate on the "ttft_max_ms" field.
func TtftMaxMsEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldTtftMaxMs, v))
}

// TtftMaxMsNEQ applies the NEQ predicate on the "ttft_max_ms" field.
func TtftMaxMsNEQ(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldTtftMaxMs, v))
}

// TtftMaxMsIn applies the In predicate on the "ttft_max_ms" field.
func TtftMaxMsIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldTtftMaxMs, vs...))
}

// TtftMaxMsNotIn applies the NotIn predicate on the "ttft_max_ms" field.
func TtftMaxMsNotIn(vs ...int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldTtftMaxMs, vs...))
}

// TtftMaxMsGT applies the GT predicate on the "ttft_max_ms" field.
func TtftMaxMsGT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldTtftMaxMs, v))
}

// TtftMaxMsGTE applies the GTE predicate on the "ttft_max_ms" field.
func TtftMaxMsGTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldTtftMaxMs, v))
}

// TtftMaxMsLT applies the LT predicate on the "ttft_max_ms" field.
func TtftMaxMsLT(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldTtftMaxMs, v))
}

// TtftMaxMsLTE applies the LTE predicate on the "ttft_max_ms" field.
func TtftMaxMsLTE(v int64) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldTtftMaxMs, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageStat {
	return predicate.UsageStat(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageStat) predicate.UsageStat {
	return predicate.UsageStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageStat) predicate.UsageStat {
	return predicate.UsageStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageStat) predicate.UsageStat {
	return predicate.UsageStat(sql.NotPredicates(p))
}
