// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/account"
	"github.com/is7qin/c3api/internal/ent/accountext"
)

// AccountExtCreate is the builder for creating a AccountExt entity.
type AccountExtCreate struct {
	config
	mutation *AccountExtMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountExtCreate) SetAccountID(v int64) *AccountExtCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetCredentialType sets the "credential_type" field.
func (_c *AccountExtCreate) SetCredentialType(v string) *AccountExtCreate {
	_c.mutation.SetCredentialType(v)
	return _c
}

// SetCodexAccountID sets the "codex_account_id" field.
func (_c *AccountExtCreate) SetCodexAccountID(v string) *AccountExtCreate {
	_c.mutation.SetCodexAccountID(v)
	return _c
}

// SetNillableCodexAccountID sets the "codex_account_id" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableCodexAccountID(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetCodexAccountID(*v)
	}
	return _c
}

// SetInstallationID sets the "installation_id" field.
func (_c *AccountExtCreate) SetInstallationID(v string) *AccountExtCreate {
	_c.mutation.SetInstallationID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AccountExtCreate) SetSessionID(v string) *AccountExtCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableSessionID(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetThreadID sets the "thread_id" field.
func (_c *AccountExtCreate) SetThreadID(v string) *AccountExtCreate {
	_c.mutation.SetThreadID(v)
	return _c
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableThreadID(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetThreadID(*v)
	}
	return _c
}

// SetWindowID sets the "window_id" field.
func (_c *AccountExtCreate) SetWindowID(v string) *AccountExtCreate {
	_c.mutation.SetWindowID(v)
	return _c
}

// SetNillableWindowID sets the "window_id" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableWindowID(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetWindowID(*v)
	}
	return _c
}

// SetOauthToken sets the "oauth_token" field.
func (_c *AccountExtCreate) SetOauthToken(v string) *AccountExtCreate {
	_c.mutation.SetOauthToken(v)
	return _c
}

// SetNillableOauthToken sets the "oauth_token" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableOauthToken(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetOauthToken(*v)
	}
	return _c
}

// SetOauthRefreshToken sets the "oauth_refresh_token" field.
func (_c *AccountExtCreate) SetOauthRefreshToken(v string) *AccountExtCreate {
	_c.mutation.SetOauthRefreshToken(v)
	return _c
}

// SetNillableOauthRefreshToken sets the "oauth_refresh_token" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableOauthRefreshToken(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetOauthRefreshToken(*v)
	}
	return _c
}

// SetOauthExpiresAt sets the "oauth_expires_at" field.
func (_c *AccountExtCreate) SetOauthExpiresAt(v time.Time) *AccountExtCreate {
	_c.mutation.SetOauthExpiresAt(v)
	return _c
}

// SetNillableOauthExpiresAt sets the "oauth_expires_at" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableOauthExpiresAt(v *time.Time) *AccountExtCreate {
	if v != nil {
		_c.SetOauthExpiresAt(*v)
	}
	return _c
}

// SetPatKey sets the "pat_key" field.
func (_c *AccountExtCreate) SetPatKey(v string) *AccountExtCreate {
	_c.mutation.SetPatKey(v)
	return _c
}

// SetNillablePatKey sets the "pat_key" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillablePatKey(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetPatKey(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *AccountExtCreate) SetEmail(v string) *AccountExtCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *AccountExtCreate) SetNillableEmail(v *string) *AccountExtCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountExtCreate) SetID(v int64) *AccountExtCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountExtCreate) SetAccount(v *Account) *AccountExtCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountExtMutation object of the builder.
func (_c *AccountExtCreate) Mutation() *AccountExtMutation {
	return _c.mutation
}

// Save creates the AccountExt in the database.
func (_c *AccountExtCreate) Save(ctx context.Context) (*AccountExt, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountExtCreate) SaveX(ctx context.Context) *AccountExt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountExtCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountExtCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountExtCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountExt.account_id"`)}
	}
	if _, ok := _c.mutation.CredentialType(); !ok {
		return &ValidationError{Name: "credential_type", err: errors.New(`ent: missing required field "AccountExt.credential_type"`)}
	}
	if _, ok := _c.mutation.InstallationID(); !ok {
		return &ValidationError{Name: "installation_id", err: errors.New(`ent: missing required field "AccountExt.installation_id"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountExt.account"`)}
	}
	return nil
}

func (_c *AccountExtCreate) sqlSave(ctx context.Context) (*AccountExt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountExtCreate) createSpec() (*AccountExt, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountExt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountext.Table, sqlgraph.NewFieldSpec(accountext.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CredentialType(); ok {
		_spec.SetField(accountext.FieldCredentialType, field.TypeString, value)
		_node.CredentialType = value
	}
	if value, ok := _c.mutation.CodexAccountID(); ok {
		_spec.SetField(accountext.FieldCodexAccountID, field.TypeString, value)
		_node.CodexAccountID = &value
	}
	if value, ok := _c.mutation.InstallationID(); ok {
		_spec.SetField(accountext.FieldInstallationID, field.TypeString, value)
		_node.InstallationID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(accountext.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.ThreadID(); ok {
		_spec.SetField(accountext.FieldThreadID, field.TypeString, value)
		_node.ThreadID = &value
	}
	if value, ok := _c.mutation.WindowID(); ok {
		_spec.SetField(accountext.FieldWindowID, field.TypeString, value)
		_node.WindowID = &value
	}
	if value, ok := _c.mutation.OauthToken(); ok {
		_spec.SetField(accountext.FieldOauthToken, field.TypeString, value)
		_node.OauthToken = &value
	}
	if value, ok := _c.mutation.OauthRefreshToken(); ok {
		_spec.SetField(accountext.FieldOauthRefreshToken, field.TypeString, value)
		_node.OauthRefreshToken = &value
	}
	if value, ok := _c.mutation.OauthExpiresAt(); ok {
		_spec.SetField(accountext.FieldOauthExpiresAt, field.TypeTime, value)
		_node.OauthExpiresAt = &value
	}
	if value, ok := _c.mutation.PatKey(); ok {
		_spec.SetField(accountext.FieldPatKey, field.TypeString, value)
		_node.PatKey = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(accountext.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountext.AccountTable,
			Columns: []string{accountext.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountExt.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountExtUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountExtCreate) OnConflict(opts ...sql.ConflictOption) *AccountExtUpsertOne {
	_c.conflict = opts
	return &AccountExtUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountExt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountExtCreate) OnConflictColumns(columns ...string) *AccountExtUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountExtUpsertOne{
		create: _c,
	}
}

type (
	// AccountExtUpsertOne is the builder for "upsert"-ing
	//  one AccountExt node.
	AccountExtUpsertOne struct {
		create *AccountExtCreate
	}

	// AccountExtUpsert is the "OnConflict" setter.
	AccountExtUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountExtUpsert) SetAccountID(v int64) *AccountExtUpsert {
	u.Set(accountext.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateAccountID() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldAccountID)
	return u
}

// SetCredentialType sets the "credential_type" field.
func (u *AccountExtUpsert) SetCredentialType(v string) *AccountExtUpsert {
	u.Set(accountext.FieldCredentialType, v)
	return u
}

// UpdateCredentialType sets the "credential_type" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateCredentialType() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldCredentialType)
	return u
}

// SetCodexAccountID sets the "codex_account_id" field.
func (u *AccountExtUpsert) SetCodexAccountID(v string) *AccountExtUpsert {
	u.Set(accountext.FieldCodexAccountID, v)
	return u
}

// UpdateCodexAccountID sets the "codex_account_id" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateCodexAccountID() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldCodexAccountID)
	return u
}

// ClearCodexAccountID clears the value of the "codex_account_id" field.
func (u *AccountExtUpsert) ClearCodexAccountID() *AccountExtUpsert {
	u.SetNull(accountext.FieldCodexAccountID)
	return u
}

// SetInstallationID sets the "installation_id" field.
func (u *AccountExtUpsert) SetInstallationID(v string) *AccountExtUpsert {
	u.Set(accountext.FieldInstallationID, v)
	return u
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateInstallationID() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldInstallationID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *AccountExtUpsert) SetSessionID(v string) *AccountExtUpsert {
	u.Set(accountext.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateSessionID() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AccountExtUpsert) ClearSessionID() *AccountExtUpsert {
	u.SetNull(accountext.FieldSessionID)
	return u
}

// SetThreadID sets the "thread_id" field.
func (u *AccountExtUpsert) SetThreadID(v string) *AccountExtUpsert {
	u.Set(accountext.FieldThreadID, v)
	return u
}

// UpdateThreadID sets the "thread_id" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateThreadID() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldThreadID)
	return u
}

// ClearThreadID clears the value of the "thread_id" field.
func (u *AccountExtUpsert) ClearThreadID() *AccountExtUpsert {
	u.SetNull(accountext.FieldThreadID)
	return u
}

// SetWindowID sets the "window_id" field.
func (u *AccountExtUpsert) SetWindowID(v string) *AccountExtUpsert {
	u.Set(accountext.FieldWindowID, v)
	return u
}

// UpdateWindowID sets the "window_id" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateWindowID() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldWindowID)
	return u
}

// ClearWindowID clears the value of the "window_id" field.
func (u *AccountExtUpsert) ClearWindowID() *AccountExtUpsert {
	u.SetNull(accountext.FieldWindowID)
	return u
}

// SetOauthToken sets the "oauth_token" field.
func (u *AccountExtUpsert) SetOauthToken(v string) *AccountExtUpsert {
	u.Set(accountext.FieldOauthToken, v)
	return u
}

// UpdateOauthToken sets the "oauth_token" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateOauthToken() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldOauthToken)
	return u
}

// ClearOauthToken clears the value of the "oauth_token" field.
func (u *AccountExtUpsert) ClearOauthToken() *AccountExtUpsert {
	u.SetNull(accountext.FieldOauthToken)
	return u
}

// SetOauthRefreshToken sets the "oauth_refresh_token" field.
func (u *AccountExtUpsert) SetOauthRefreshToken(v string) *AccountExtUpsert {
	u.Set(accountext.FieldOauthRefreshToken, v)
	return u
}

// UpdateOauthRefreshToken sets the "oauth_refresh_token" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateOauthRefreshToken() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldOauthRefreshToken)
	return u
}

// ClearOauthRefreshToken clears the value of the "oauth_refresh_token" field.
func (u *AccountExtUpsert) ClearOauthRefreshToken() *AccountExtUpsert {
	u.SetNull(accountext.FieldOauthRefreshToken)
	return u
}

// SetOauthExpiresAt sets the "oauth_expires_at" field.
func (u *AccountExtUpsert) SetOauthExpiresAt(v time.Time) *AccountExtUpsert {
	u.Set(accountext.FieldOauthExpiresAt, v)
	return u
}

// UpdateOauthExpiresAt sets the "oauth_expires_at" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateOauthExpiresAt() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldOauthExpiresAt)
	return u
}

// ClearOauthExpiresAt clears the value of the "oauth_expires_at" field.
func (u *AccountExtUpsert) ClearOauthExpiresAt() *AccountExtUpsert {
	u.SetNull(accountext.FieldOauthExpiresAt)
	return u
}

// SetPatKey sets the "pat_key" field.
func (u *AccountExtUpsert) SetPatKey(v string) *AccountExtUpsert {
	u.Set(accountext.FieldPatKey, v)
	return u
}

// UpdatePatKey sets the "pat_key" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdatePatKey() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldPatKey)
	return u
}

// ClearPatKey clears the value of the "pat_key" field.
func (u *AccountExtUpsert) ClearPatKey() *AccountExtUpsert {
	u.SetNull(accountext.FieldPatKey)
	return u
}

// SetEmail sets the "email" field.
func (u *AccountExtUpsert) SetEmail(v string) *AccountExtUpsert {
	u.Set(accountext.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AccountExtUpsert) UpdateEmail() *AccountExtUpsert {
	u.SetExcluded(accountext.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *AccountExtUpsert) ClearEmail() *AccountExtUpsert {
	u.SetNull(accountext.FieldEmail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AccountExt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountext.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountExtUpsertOne) UpdateNewValues() *AccountExtUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(accountext.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountExt.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountExtUpsertOne) Ignore() *AccountExtUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountExtUpsertOne) DoNothing() *AccountExtUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountExtCreate.OnConflict
// documentation for more info.
func (u *AccountExtUpsertOne) Update(set func(*AccountExtUpsert)) *AccountExtUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountExtUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountExtUpsertOne) SetAccountID(v int64) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateAccountID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateAccountID()
	})
}

// SetCredentialType sets the "credential_type" field.
func (u *AccountExtUpsertOne) SetCredentialType(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetCredentialType(v)
	})
}

// UpdateCredentialType sets the "credential_type" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateCredentialType() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateCredentialType()
	})
}

// SetCodexAccountID sets the "codex_account_id" field.
func (u *AccountExtUpsertOne) SetCodexAccountID(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetCodexAccountID(v)
	})
}

// UpdateCodexAccountID sets the "codex_account_id" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateCodexAccountID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateCodexAccountID()
	})
}

// ClearCodexAccountID clears the value of the "codex_account_id" field.
func (u *AccountExtUpsertOne) ClearCodexAccountID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearCodexAccountID()
	})
}

// SetInstallationID sets the "installation_id" field.
func (u *AccountExtUpsertOne) SetInstallationID(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetInstallationID(v)
	})
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateInstallationID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateInstallationID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AccountExtUpsertOne) SetSessionID(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateSessionID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AccountExtUpsertOne) ClearSessionID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearSessionID()
	})
}

// SetThreadID sets the "thread_id" field.
func (u *AccountExtUpsertOne) SetThreadID(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetThreadID(v)
	})
}

// UpdateThreadID sets the "thread_id" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateThreadID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateThreadID()
	})
}

// ClearThreadID clears the value of the "thread_id" field.
func (u *AccountExtUpsertOne) ClearThreadID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearThreadID()
	})
}

// SetWindowID sets the "window_id" field.
func (u *AccountExtUpsertOne) SetWindowID(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetWindowID(v)
	})
}

// UpdateWindowID sets the "window_id" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateWindowID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateWindowID()
	})
}

// ClearWindowID clears the value of the "window_id" field.
func (u *AccountExtUpsertOne) ClearWindowID() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearWindowID()
	})
}

// SetOauthToken sets the "oauth_token" field.
func (u *AccountExtUpsertOne) SetOauthToken(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetOauthToken(v)
	})
}

// UpdateOauthToken sets the "oauth_token" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateOauthToken() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateOauthToken()
	})
}

// ClearOauthToken clears the value of the "oauth_token" field.
func (u *AccountExtUpsertOne) ClearOauthToken() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearOauthToken()
	})
}

// SetOauthRefreshToken sets the "oauth_refresh_token" field.
func (u *AccountExtUpsertOne) SetOauthRefreshToken(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetOauthRefreshToken(v)
	})
}

// UpdateOauthRefreshToken sets the "oauth_refresh_token" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateOauthRefreshToken() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateOauthRefreshToken()
	})
}

// ClearOauthRefreshToken clears the value of the "oauth_refresh_token" field.
func (u *AccountExtUpsertOne) ClearOauthRefreshToken() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearOauthRefreshToken()
	})
}

// SetOauthExpiresAt sets the "oauth_expires_at" field.
func (u *AccountExtUpsertOne) SetOauthExpiresAt(v time.Time) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetOauthExpiresAt(v)
	})
}

// UpdateOauthExpiresAt sets the "oauth_expires_at" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateOauthExpiresAt() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateOauthExpiresAt()
	})
}

// ClearOauthExpiresAt clears the value of the "oauth_expires_at" field.
func (u *AccountExtUpsertOne) ClearOauthExpiresAt() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearOauthExpiresAt()
	})
}

// SetPatKey sets the "pat_key" field.
func (u *AccountExtUpsertOne) SetPatKey(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetPatKey(v)
	})
}

// UpdatePatKey sets the "pat_key" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdatePatKey() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdatePatKey()
	})
}

// ClearPatKey clears the value of the "pat_key" field.
func (u *AccountExtUpsertOne) ClearPatKey() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearPatKey()
	})
}

// SetEmail sets the "email" field.
func (u *AccountExtUpsertOne) SetEmail(v string) *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AccountExtUpsertOne) UpdateEmail() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *AccountExtUpsertOne) ClearEmail() *AccountExtUpsertOne {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearEmail()
	})
}

// Exec executes the query.
func (u *AccountExtUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountExtCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountExtUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountExtUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountExtUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountExtCreateBulk is the builder for creating many AccountExt entities in bulk.
type AccountExtCreateBulk struct {
	config
	err      error
	builders []*AccountExtCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountExt entities in the database.
func (_c *AccountExtCreateBulk) Save(ctx context.Context) ([]*AccountExt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountExt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountExtMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountExtCreateBulk) SaveX(ctx context.Context) []*AccountExt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountExtCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountExtCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountExt.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountExtUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountExtCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountExtUpsertBulk {
	_c.conflict = opts
	return &AccountExtUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountExt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountExtCreateBulk) OnConflictColumns(columns ...string) *AccountExtUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountExtUpsertBulk{
		create: _c,
	}
}

// AccountExtUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountExt nodes.
type AccountExtUpsertBulk struct {
	create *AccountExtCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountExt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountext.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountExtUpsertBulk) UpdateNewValues() *AccountExtUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(accountext.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountExt.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountExtUpsertBulk) Ignore() *AccountExtUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountExtUpsertBulk) DoNothing() *AccountExtUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountExtCreateBulk.OnConflict
// documentation for more info.
func (u *AccountExtUpsertBulk) Update(set func(*AccountExtUpsert)) *AccountExtUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountExtUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountExtUpsertBulk) SetAccountID(v int64) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateAccountID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateAccountID()
	})
}

// SetCredentialType sets the "credential_type" field.
func (u *AccountExtUpsertBulk) SetCredentialType(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetCredentialType(v)
	})
}

// UpdateCredentialType sets the "credential_type" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateCredentialType() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateCredentialType()
	})
}

// SetCodexAccountID sets the "codex_account_id" field.
func (u *AccountExtUpsertBulk) SetCodexAccountID(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetCodexAccountID(v)
	})
}

// UpdateCodexAccountID sets the "codex_account_id" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateCodexAccountID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateCodexAccountID()
	})
}

// ClearCodexAccountID clears the value of the "codex_account_id" field.
func (u *AccountExtUpsertBulk) ClearCodexAccountID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearCodexAccountID()
	})
}

// SetInstallationID sets the "installation_id" field.
func (u *AccountExtUpsertBulk) SetInstallationID(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetInstallationID(v)
	})
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateInstallationID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateInstallationID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AccountExtUpsertBulk) SetSessionID(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateSessionID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AccountExtUpsertBulk) ClearSessionID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearSessionID()
	})
}

// SetThreadID sets the "thread_id" field.
func (u *AccountExtUpsertBulk) SetThreadID(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetThreadID(v)
	})
}

// UpdateThreadID sets the "thread_id" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateThreadID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateThreadID()
	})
}

// ClearThreadID clears the value of the "thread_id" field.
func (u *AccountExtUpsertBulk) ClearThreadID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearThreadID()
	})
}

// SetWindowID sets the "window_id" field.
func (u *AccountExtUpsertBulk) SetWindowID(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetWindowID(v)
	})
}

// UpdateWindowID sets the "window_id" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateWindowID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateWindowID()
	})
}

// ClearWindowID clears the value of the "window_id" field.
func (u *AccountExtUpsertBulk) ClearWindowID() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearWindowID()
	})
}

// SetOauthToken sets the "oauth_token" field.
func (u *AccountExtUpsertBulk) SetOauthToken(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetOauthToken(v)
	})
}

// UpdateOauthToken sets the "oauth_token" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateOauthToken() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateOauthToken()
	})
}

// ClearOauthToken clears the value of the "oauth_token" field.
func (u *AccountExtUpsertBulk) ClearOauthToken() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearOauthToken()
	})
}

// SetOauthRefreshToken sets the "oauth_refresh_token" field.
func (u *AccountExtUpsertBulk) SetOauthRefreshToken(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetOauthRefreshToken(v)
	})
}

// UpdateOauthRefreshToken sets the "oauth_refresh_token" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateOauthRefreshToken() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateOauthRefreshToken()
	})
}

// ClearOauthRefreshToken clears the value of the "oauth_refresh_token" field.
func (u *AccountExtUpsertBulk) ClearOauthRefreshToken() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearOauthRefreshToken()
	})
}

// SetOauthExpiresAt sets the "oauth_expires_at" field.
func (u *AccountExtUpsertBulk) SetOauthExpiresAt(v time.Time) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetOauthExpiresAt(v)
	})
}

// UpdateOauthExpiresAt sets the "oauth_expires_at" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateOauthExpiresAt() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateOauthExpiresAt()
	})
}

// ClearOauthExpiresAt clears the value of the "oauth_expires_at" field.
func (u *AccountExtUpsertBulk) ClearOauthExpiresAt() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearOauthExpiresAt()
	})
}

// SetPatKey sets the "pat_key" field.
func (u *AccountExtUpsertBulk) SetPatKey(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetPatKey(v)
	})
}

// UpdatePatKey sets the "pat_key" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdatePatKey() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdatePatKey()
	})
}

// ClearPatKey clears the value of the "pat_key" field.
func (u *AccountExtUpsertBulk) ClearPatKey() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearPatKey()
	})
}

// SetEmail sets the "email" field.
func (u *AccountExtUpsertBulk) SetEmail(v string) *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AccountExtUpsertBulk) UpdateEmail() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *AccountExtUpsertBulk) ClearEmail() *AccountExtUpsertBulk {
	return u.Update(func(s *AccountExtUpsert) {
		s.ClearEmail()
	})
}

// Exec executes the query.
func (u *AccountExtUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountExtCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountExtCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountExtUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
