// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/balancelog"
)

// BalanceLogCreate is the builder for creating a BalanceLog entity.
type BalanceLogCreate struct {
	config
	mutation *BalanceLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *BalanceLogCreate) SetUserID(v int64) *BalanceLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *BalanceLogCreate) SetAmount(v int64) *BalanceLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *BalanceLogCreate) SetBalanceAfter(v int64) *BalanceLogCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *BalanceLogCreate) SetSource(v balancelog.Source) *BalanceLogCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *BalanceLogCreate) SetOperatorID(v int64) *BalanceLogCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *BalanceLogCreate) SetNillableOperatorID(v *int64) *BalanceLogCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *BalanceLogCreate) SetNote(v string) *BalanceLogCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *BalanceLogCreate) SetNillableNote(v *string) *BalanceLogCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceLogCreate) SetCreatedAt(v time.Time) *BalanceLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalanceLogCreate) SetNillableCreatedAt(v *time.Time) *BalanceLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BalanceLogCreate) SetID(v int64) *BalanceLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BalanceLogMutation object of the builder.
func (_c *BalanceLogCreate) Mutation() *BalanceLogMutation {
	return _c.mutation
}

// Save creates the BalanceLog in the database.
func (_c *BalanceLogCreate) Save(ctx context.Context) (*BalanceLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceLogCreate) SaveX(ctx context.Context) *BalanceLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceLogCreate) defaults() {
	if _, ok := _c.mutation.OperatorID(); !ok {
		v := balancelog.DefaultOperatorID
		_c.mutation.SetOperatorID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balancelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BalanceLog.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "BalanceLog.amount"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "BalanceLog.balance_after"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "BalanceLog.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := balancelog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OperatorID(); !ok {
		return &ValidationError{Name: "operator_id", err: errors.New(`ent: missing required field "BalanceLog.operator_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalanceLog.created_at"`)}
	}
	return nil
}

func (_c *BalanceLogCreate) sqlSave(ctx context.Context) (*BalanceLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceLogCreate) createSpec() (*BalanceLog, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancelog.Table, sqlgraph.NewFieldSpec(balancelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(balancelog.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(balancelog.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(balancelog.FieldBalanceAfter, field.TypeInt64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(balancelog.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(balancelog.FieldOperatorID, field.TypeInt64, value)
		_node.OperatorID = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(balancelog.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balancelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceLog.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceLogCreate) OnConflict(opts ...sql.ConflictOption) *BalanceLogUpsertOne {
	_c.conflict = opts
	return &BalanceLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceLogCreate) OnConflictColumns(columns ...string) *BalanceLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceLogUpsertOne{
		create: _c,
	}
}

type (
	// BalanceLogUpsertOne is the builder for "upsert"-ing
	//  one BalanceLog node.
	BalanceLogUpsertOne struct {
		create *BalanceLogCreate
	}

	// BalanceLogUpsert is the "OnConflict" setter.
	BalanceLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *BalanceLogUpsert) SetUserID(v int64) *BalanceLogUpsert {
	u.Set(balancelog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateUserID() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceLogUpsert) AddUserID(v int64) *BalanceLogUpsert {
	u.Add(balancelog.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *BalanceLogUpsert) SetAmount(v int64) *BalanceLogUpsert {
	u.Set(balancelog.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateAmount() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *BalanceLogUpsert) AddAmount(v int64) *BalanceLogUpsert {
	u.Add(balancelog.FieldAmount, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BalanceLogUpsert) SetBalanceAfter(v int64) *BalanceLogUpsert {
	u.Set(balancelog.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateBalanceAfter() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BalanceLogUpsert) AddBalanceAfter(v int64) *BalanceLogUpsert {
	u.Add(balancelog.FieldBalanceAfter, v)
	return u
}

// SetSource sets the "source" field.
func (u *BalanceLogUpsert) SetSource(v balancelog.Source) *BalanceLogUpsert {
	u.Set(balancelog.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateSource() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldSource)
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *BalanceLogUpsert) SetOperatorID(v int64) *BalanceLogUpsert {
	u.Set(balancelog.FieldOperatorID, v)
	return u
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateOperatorID() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldOperatorID)
	return u
}

// AddOperatorID adds v to the "operator_id" field.
func (u *BalanceLogUpsert) AddOperatorID(v int64) *BalanceLogUpsert {
	u.Add(balancelog.FieldOperatorID, v)
	return u
}

// SetNote sets the "note" field.
func (u *BalanceLogUpsert) SetNote(v string) *BalanceLogUpsert {
	u.Set(balancelog.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateNote() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *BalanceLogUpsert) ClearNote() *BalanceLogUpsert {
	u.SetNull(balancelog.FieldNote)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *BalanceLogUpsert) SetCreatedAt(v time.Time) *BalanceLogUpsert {
	u.Set(balancelog.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *BalanceLogUpsert) UpdateCreatedAt() *BalanceLogUpsert {
	u.SetExcluded(balancelog.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BalanceLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(balancelog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BalanceLogUpsertOne) UpdateNewValues() *BalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(balancelog.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceLogUpsertOne) Ignore() *BalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceLogUpsertOne) DoNothing() *BalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceLogCreate.OnConflict
// documentation for more info.
func (u *BalanceLogUpsertOne) Update(set func(*BalanceLogUpsert)) *BalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceLogUpsertOne) SetUserID(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceLogUpsertOne) AddUserID(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateUserID() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceLogUpsertOne) SetAmount(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceLogUpsertOne) AddAmount(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateAmount() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BalanceLogUpsertOne) SetBalanceAfter(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BalanceLogUpsertOne) AddBalanceAfter(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateBalanceAfter() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetSource sets the "source" field.
func (u *BalanceLogUpsertOne) SetSource(v balancelog.Source) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateSource() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateSource()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *BalanceLogUpsertOne) SetOperatorID(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *BalanceLogUpsertOne) AddOperatorID(v int64) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateOperatorID() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateOperatorID()
	})
}

// SetNote sets the "note" field.
func (u *BalanceLogUpsertOne) SetNote(v string) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateNote() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *BalanceLogUpsertOne) ClearNote() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.ClearNote()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *BalanceLogUpsertOne) SetCreatedAt(v time.Time) *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *BalanceLogUpsertOne) UpdateCreatedAt() *BalanceLogUpsertOne {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *BalanceLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceLogCreateBulk is the builder for creating many BalanceLog entities in bulk.
type BalanceLogCreateBulk struct {
	config
	err      error
	builders []*BalanceLogCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceLog entities in the database.
func (_c *BalanceLogCreateBulk) Save(ctx context.Context) ([]*BalanceLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceLogCreateBulk) SaveX(ctx context.Context) []*BalanceLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceLogUpsertBulk {
	_c.conflict = opts
	return &BalanceLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceLogCreateBulk) OnConflictColumns(columns ...string) *BalanceLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceLogUpsertBulk{
		create: _c,
	}
}

// BalanceLogUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceLog nodes.
type BalanceLogUpsertBulk struct {
	create *BalanceLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(balancelog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BalanceLogUpsertBulk) UpdateNewValues() *BalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(balancelog.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceLogUpsertBulk) Ignore() *BalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceLogUpsertBulk) DoNothing() *BalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceLogCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceLogUpsertBulk) Update(set func(*BalanceLogUpsert)) *BalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceLogUpsertBulk) SetUserID(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceLogUpsertBulk) AddUserID(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateUserID() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceLogUpsertBulk) SetAmount(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceLogUpsertBulk) AddAmount(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateAmount() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BalanceLogUpsertBulk) SetBalanceAfter(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BalanceLogUpsertBulk) AddBalanceAfter(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateBalanceAfter() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetSource sets the "source" field.
func (u *BalanceLogUpsertBulk) SetSource(v balancelog.Source) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateSource() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateSource()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *BalanceLogUpsertBulk) SetOperatorID(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *BalanceLogUpsertBulk) AddOperatorID(v int64) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateOperatorID() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateOperatorID()
	})
}

// SetNote sets the "note" field.
func (u *BalanceLogUpsertBulk) SetNote(v string) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateNote() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *BalanceLogUpsertBulk) ClearNote() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.ClearNote()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *BalanceLogUpsertBulk) SetCreatedAt(v time.Time) *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *BalanceLogUpsertBulk) UpdateCreatedAt() *BalanceLogUpsertBulk {
	return u.Update(func(s *BalanceLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *BalanceLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
