// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/emailcode"
	"github.com/is7qin/c3api/internal/ent/predicate"
)

// EmailCodeUpdate is the builder for updating EmailCode entities.
type EmailCodeUpdate struct {
	config
	hooks    []Hook
	mutation *EmailCodeMutation
}

// Where appends a list predicates to the EmailCodeUpdate builder.
func (_u *EmailCodeUpdate) Where(ps ...predicate.EmailCode) *EmailCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailCodeUpdate) SetEmail(v string) *EmailCodeUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailCodeUpdate) SetNillableEmail(v *string) *EmailCodeUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *EmailCodeUpdate) SetPurpose(v emailcode.Purpose) *EmailCodeUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *EmailCodeUpdate) SetNillablePurpose(v *emailcode.Purpose) *EmailCodeUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetCodeSha256 sets the "code_sha256" field.
func (_u *EmailCodeUpdate) SetCodeSha256(v string) *EmailCodeUpdate {
	_u.mutation.SetCodeSha256(v)
	return _u
}

// SetNillableCodeSha256 sets the "code_sha256" field if the given value is not nil.
func (_u *EmailCodeUpdate) SetNillableCodeSha256(v *string) *EmailCodeUpdate {
	if v != nil {
		_u.SetCodeSha256(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailCodeUpdate) SetExpiresAt(v time.Time) *EmailCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailCodeUpdate) SetNillableExpiresAt(v *time.Time) *EmailCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EmailCodeUpdate) SetAttempts(v int) *EmailCodeUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EmailCodeUpdate) SetNillableAttempts(v *int) *EmailCodeUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EmailCodeUpdate) AddAttempts(v int) *EmailCodeUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EmailCodeUpdate) SetCreatedAt(v time.Time) *EmailCodeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EmailCodeUpdate) SetNillableCreatedAt(v *time.Time) *EmailCodeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailCodeUpdate) SetUpdatedAt(v time.Time) *EmailCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EmailCodeMutation object of the builder.
func (_u *EmailCodeUpdate) Mutation() *EmailCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailCodeUpdate) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := emailcode.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "EmailCode.purpose": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailcode.Table, emailcode.Columns, sqlgraph.NewFieldSpec(emailcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailcode.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(emailcode.FieldPurpose, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CodeSha256(); ok {
		_spec.SetField(emailcode.FieldCodeSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(emailcode.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(emailcode.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(emailcode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailCodeUpdateOne is the builder for updating a single EmailCode entity.
type EmailCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailCodeMutation
}

// SetEmail sets the "email" field.
func (_u *EmailCodeUpdateOne) SetEmail(v string) *EmailCodeUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailCodeUpdateOne) SetNillableEmail(v *string) *EmailCodeUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *EmailCodeUpdateOne) SetPurpose(v emailcode.Purpose) *EmailCodeUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *EmailCodeUpdateOne) SetNillablePurpose(v *emailcode.Purpose) *EmailCodeUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetCodeSha256 sets the "code_sha256" field.
func (_u *EmailCodeUpdateOne) SetCodeSha256(v string) *EmailCodeUpdateOne {
	_u.mutation.SetCodeSha256(v)
	return _u
}

// SetNillableCodeSha256 sets the "code_sha256" field if the given value is not nil.
func (_u *EmailCodeUpdateOne) SetNillableCodeSha256(v *string) *EmailCodeUpdateOne {
	if v != nil {
		_u.SetCodeSha256(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailCodeUpdateOne) SetExpiresAt(v time.Time) *EmailCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *EmailCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EmailCodeUpdateOne) SetAttempts(v int) *EmailCodeUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EmailCodeUpdateOne) SetNillableAttempts(v *int) *EmailCodeUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EmailCodeUpdateOne) AddAttempts(v int) *EmailCodeUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EmailCodeUpdateOne) SetCreatedAt(v time.Time) *EmailCodeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EmailCodeUpdateOne) SetNillableCreatedAt(v *time.Time) *EmailCodeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailCodeUpdateOne) SetUpdatedAt(v time.Time) *EmailCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EmailCodeMutation object of the builder.
func (_u *EmailCodeUpdateOne) Mutation() *EmailCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailCodeUpdate builder.
func (_u *EmailCodeUpdateOne) Where(ps ...predicate.EmailCode) *EmailCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailCodeUpdateOne) Select(field string, fields ...string) *EmailCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailCode entity.
func (_u *EmailCodeUpdateOne) Save(ctx context.Context) (*EmailCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailCodeUpdateOne) SaveX(ctx context.Context) *EmailCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := emailcode.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "EmailCode.purpose": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailCodeUpdateOne) sqlSave(ctx context.Context) (_node *EmailCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailcode.Table, emailcode.Columns, sqlgraph.NewFieldSpec(emailcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailcode.FieldID)
		for _, f := range fields {
			if !emailcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailcode.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(emailcode.FieldPurpose, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CodeSha256(); ok {
		_spec.SetField(emailcode.FieldCodeSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(emailcode.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(emailcode.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(emailcode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailcode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EmailCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
