// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/supplierbalance"
)

// SupplierBalance is the model entity for the SupplierBalance schema.
type SupplierBalance struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SupplierUserID holds the value of the "supplier_user_id" field.
	SupplierUserID int64 `json:"supplier_user_id,omitempty"`
	// Available holds the value of the "available" field.
	Available int64 `json:"available,omitempty"`
	// LifetimeCredited holds the value of the "lifetime_credited" field.
	LifetimeCredited int64 `json:"lifetime_credited,omitempty"`
	// LifetimePaid holds the value of the "lifetime_paid" field.
	LifetimePaid int64 `json:"lifetime_paid,omitempty"`
	// ShareBp holds the value of the "share_bp" field.
	ShareBp *int `json:"share_bp,omitempty"`
	// FreezeHours holds the value of the "freeze_hours" field.
	FreezeHours *int `json:"freeze_hours,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierBalance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplierbalance.FieldID, supplierbalance.FieldSupplierUserID, supplierbalance.FieldAvailable, supplierbalance.FieldLifetimeCredited, supplierbalance.FieldLifetimePaid, supplierbalance.FieldShareBp, supplierbalance.FieldFreezeHours:
			values[i] = new(sql.NullInt64)
		case supplierbalance.FieldCreatedAt, supplierbalance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierBalance fields.
func (_m *SupplierBalance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplierbalance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supplierbalance.FieldSupplierUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_user_id", values[i])
			} else if value.Valid {
				_m.SupplierUserID = value.Int64
			}
		case supplierbalance.FieldAvailable:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field available", values[i])
			} else if value.Valid {
				_m.Available = value.Int64
			}
		case supplierbalance.FieldLifetimeCredited:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_credited", values[i])
			} else if value.Valid {
				_m.LifetimeCredited = value.Int64
			}
		case supplierbalance.FieldLifetimePaid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_paid", values[i])
			} else if value.Valid {
				_m.LifetimePaid = value.Int64
			}
		case supplierbalance.FieldShareBp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_bp", values[i])
			} else if value.Valid {
				_m.ShareBp = new(int)
				*_m.ShareBp = int(value.Int64)
			}
		case supplierbalance.FieldFreezeHours:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field freeze_hours", values[i])
			} else if value.Valid {
				_m.FreezeHours = new(int)
				*_m.FreezeHours = int(value.Int64)
			}
		case supplierbalance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supplierbalance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupplierBalance.
// This includes values selected through modifiers, order, etc.
func (_m *SupplierBalance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SupplierBalance.
// Note that you need to call SupplierBalance.Unwrap() before calling this method if this SupplierBalance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupplierBalance) Update() *SupplierBalanceUpdateOne {
	return NewSupplierBalanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupplierBalance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupplierBalance) Unwrap() *SupplierBalance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierBalance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupplierBalance) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierBalance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("supplier_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplierUserID))
	builder.WriteString(", ")
	builder.WriteString("available=")
	builder.WriteString(fmt.Sprintf("%v", _m.Available))
	builder.WriteString(", ")
	builder.WriteString("lifetime_credited=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeCredited))
	builder.WriteString(", ")
	builder.WriteString("lifetime_paid=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimePaid))
	builder.WriteString(", ")
	if v := _m.ShareBp; v != nil {
		builder.WriteString("share_bp=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FreezeHours; v != nil {
		builder.WriteString("freeze_hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupplierBalances is a parsable slice of SupplierBalance.
type SupplierBalances []*SupplierBalance
