// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/supplierreconciliation"
)

// SupplierReconciliation is the model entity for the SupplierReconciliation schema.
type SupplierReconciliation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SupplierUserID holds the value of the "supplier_user_id" field.
	SupplierUserID int64 `json:"supplier_user_id,omitempty"`
	// SourceDay holds the value of the "source_day" field.
	SourceDay time.Time `json:"source_day,omitempty"`
	// GrossCost holds the value of the "gross_cost" field.
	GrossCost int64 `json:"gross_cost,omitempty"`
	// Earned holds the value of the "earned" field.
	Earned int64 `json:"earned,omitempty"`
	// RowCount holds the value of the "row_count" field.
	RowCount int64 `json:"row_count,omitempty"`
	// State holds the value of the "state" field.
	State supplierreconciliation.State `json:"state,omitempty"`
	// ClosedRevision holds the value of the "closed_revision" field.
	ClosedRevision *int64 `json:"closed_revision,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt     *time.Time `json:"closed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierReconciliation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplierreconciliation.FieldID, supplierreconciliation.FieldSupplierUserID, supplierreconciliation.FieldGrossCost, supplierreconciliation.FieldEarned, supplierreconciliation.FieldRowCount, supplierreconciliation.FieldClosedRevision:
			values[i] = new(sql.NullInt64)
		case supplierreconciliation.FieldState:
			values[i] = new(sql.NullString)
		case supplierreconciliation.FieldSourceDay, supplierreconciliation.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierReconciliation fields.
func (_m *SupplierReconciliation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplierreconciliation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supplierreconciliation.FieldSupplierUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_user_id", values[i])
			} else if value.Valid {
				_m.SupplierUserID = value.Int64
			}
		case supplierreconciliation.FieldSourceDay:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_day", values[i])
			} else if value.Valid {
				_m.SourceDay = value.Time
			}
		case supplierreconciliation.FieldGrossCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gross_cost", values[i])
			} else if value.Valid {
				_m.GrossCost = value.Int64
			}
		case supplierreconciliation.FieldEarned:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field earned", values[i])
			} else if value.Valid {
				_m.Earned = value.Int64
			}
		case supplierreconciliation.FieldRowCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field row_count", values[i])
			} else if value.Valid {
				_m.RowCount = value.Int64
			}
		case supplierreconciliation.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = supplierreconciliation.State(value.String)
			}
		case supplierreconciliation.FieldClosedRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field closed_revision", values[i])
			} else if value.Valid {
				_m.ClosedRevision = new(int64)
				*_m.ClosedRevision = value.Int64
			}
		case supplierreconciliation.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupplierReconciliation.
// This includes values selected through modifiers, order, etc.
func (_m *SupplierReconciliation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SupplierReconciliation.
// Note that you need to call SupplierReconciliation.Unwrap() before calling this method if this SupplierReconciliation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupplierReconciliation) Update() *SupplierReconciliationUpdateOne {
	return NewSupplierReconciliationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupplierReconciliation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupplierReconciliation) Unwrap() *SupplierReconciliation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierReconciliation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupplierReconciliation) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierReconciliation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("supplier_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplierUserID))
	builder.WriteString(", ")
	builder.WriteString("source_day=")
	builder.WriteString(_m.SourceDay.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("gross_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrossCost))
	builder.WriteString(", ")
	builder.WriteString("earned=")
	builder.WriteString(fmt.Sprintf("%v", _m.Earned))
	builder.WriteString(", ")
	builder.WriteString("row_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RowCount))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	if v := _m.ClosedRevision; v != nil {
		builder.WriteString("closed_revision=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SupplierReconciliations is a parsable slice of SupplierReconciliation.
type SupplierReconciliations []*SupplierReconciliation
