// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/usagelog"
)

// UsageLogCreate is the builder for creating a UsageLog entity.
type UsageLogCreate struct {
	config
	mutation *UsageLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *UsageLogCreate) SetRequestID(v string) *UsageLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *UsageLogCreate) SetClientIP(v string) *UsageLogCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableClientIP(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UsageLogCreate) SetGroupID(v int64) *UsageLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableGroupID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UsageLogCreate) SetAccountID(v int64) *UsageLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableAccountID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *UsageLogCreate) SetTemplateID(v int64) *UsageLogCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTemplateID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UsageLogCreate) SetUserID(v int64) *UsageLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableUserID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetKeyID sets the "key_id" field.
func (_c *UsageLogCreate) SetKeyID(v int64) *UsageLogCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableKeyID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetKeyID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *UsageLogCreate) SetModel(v string) *UsageLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMappedModel sets the "mapped_model" field.
func (_c *UsageLogCreate) SetMappedModel(v string) *UsageLogCreate {
	_c.mutation.SetMappedModel(v)
	return _c
}

// SetNillableMappedModel sets the "mapped_model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableMappedModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetMappedModel(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *UsageLogCreate) SetFormat(v usagelog.Format) *UsageLogCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetErrorType sets the "error_type" field.
func (_c *UsageLogCreate) SetErrorType(v string) *UsageLogCreate {
	_c.mutation.SetErrorType(v)
	return _c
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableErrorType(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetErrorType(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *UsageLogCreate) SetLatencyMs(v int64) *UsageLogCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableLatencyMs(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetTtftMs sets the "ttft_ms" field.
func (_c *UsageLogCreate) SetTtftMs(v int64) *UsageLogCreate {
	_c.mutation.SetTtftMs(v)
	return _c
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTtftMs(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTtftMs(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *UsageLogCreate) SetInputTokens(v int64) *UsageLogCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableInputTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetPriceInputMillis sets the "price_input_millis" field.
func (_c *UsageLogCreate) SetPriceInputMillis(v int64) *UsageLogCreate {
	_c.mutation.SetPriceInputMillis(v)
	return _c
}

// SetNillablePriceInputMillis sets the "price_input_millis" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePriceInputMillis(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPriceInputMillis(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *UsageLogCreate) SetOutputTokens(v int64) *UsageLogCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableOutputTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetPriceOutputMillis sets the "price_output_millis" field.
func (_c *UsageLogCreate) SetPriceOutputMillis(v int64) *UsageLogCreate {
	_c.mutation.SetPriceOutputMillis(v)
	return _c
}

// SetNillablePriceOutputMillis sets the "price_output_millis" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePriceOutputMillis(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPriceOutputMillis(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *UsageLogCreate) SetTotalTokens(v int64) *UsageLogCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTotalTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_c *UsageLogCreate) SetCacheReadTokens(v int64) *UsageLogCreate {
	_c.mutation.SetCacheReadTokens(v)
	return _c
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCacheReadTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetCacheReadTokens(*v)
	}
	return _c
}

// SetPriceCacheReadMillis sets the "price_cache_read_millis" field.
func (_c *UsageLogCreate) SetPriceCacheReadMillis(v int64) *UsageLogCreate {
	_c.mutation.SetPriceCacheReadMillis(v)
	return _c
}

// SetNillablePriceCacheReadMillis sets the "price_cache_read_millis" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePriceCacheReadMillis(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPriceCacheReadMillis(*v)
	}
	return _c
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_c *UsageLogCreate) SetCacheCreationTokens(v int64) *UsageLogCreate {
	_c.mutation.SetCacheCreationTokens(v)
	return _c
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCacheCreationTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetCacheCreationTokens(*v)
	}
	return _c
}

// SetPriceCacheCreationMillis sets the "price_cache_creation_millis" field.
func (_c *UsageLogCreate) SetPriceCacheCreationMillis(v int64) *UsageLogCreate {
	_c.mutation.SetPriceCacheCreationMillis(v)
	return _c
}

// SetNillablePriceCacheCreationMillis sets the "price_cache_creation_millis" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePriceCacheCreationMillis(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPriceCacheCreationMillis(*v)
	}
	return _c
}

// SetCallCount sets the "call_count" field.
func (_c *UsageLogCreate) SetCallCount(v int64) *UsageLogCreate {
	_c.mutation.SetCallCount(v)
	return _c
}

// SetNillableCallCount sets the "call_count" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCallCount(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetCallCount(*v)
	}
	return _c
}

// SetPricePerCallMillis sets the "price_per_call_millis" field.
func (_c *UsageLogCreate) SetPricePerCallMillis(v int64) *UsageLogCreate {
	_c.mutation.SetPricePerCallMillis(v)
	return _c
}

// SetNillablePricePerCallMillis sets the "price_per_call_millis" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePricePerCallMillis(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPricePerCallMillis(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *UsageLogCreate) SetCost(v int64) *UsageLogCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCost(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetRawCost sets the "raw_cost" field.
func (_c *UsageLogCreate) SetRawCost(v int64) *UsageLogCreate {
	_c.mutation.SetRawCost(v)
	return _c
}

// SetNillableRawCost sets the "raw_cost" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableRawCost(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetRawCost(*v)
	}
	return _c
}

// SetBillingTier sets the "billing_tier" field.
func (_c *UsageLogCreate) SetBillingTier(v string) *UsageLogCreate {
	_c.mutation.SetBillingTier(v)
	return _c
}

// SetNillableBillingTier sets the "billing_tier" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableBillingTier(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetBillingTier(*v)
	}
	return _c
}

// SetAboveHit sets the "above_hit" field.
func (_c *UsageLogCreate) SetAboveHit(v bool) *UsageLogCreate {
	_c.mutation.SetAboveHit(v)
	return _c
}

// SetNillableAboveHit sets the "above_hit" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableAboveHit(v *bool) *UsageLogCreate {
	if v != nil {
		_c.SetAboveHit(*v)
	}
	return _c
}

// SetOverdraft sets the "overdraft" field.
func (_c *UsageLogCreate) SetOverdraft(v bool) *UsageLogCreate {
	_c.mutation.SetOverdraft(v)
	return _c
}

// SetNillableOverdraft sets the "overdraft" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableOverdraft(v *bool) *UsageLogCreate {
	if v != nil {
		_c.SetOverdraft(*v)
	}
	return _c
}

// SetBilled sets the "billed" field.
func (_c *UsageLogCreate) SetBilled(v bool) *UsageLogCreate {
	_c.mutation.SetBilled(v)
	return _c
}

// SetNillableBilled sets the "billed" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableBilled(v *bool) *UsageLogCreate {
	if v != nil {
		_c.SetBilled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogCreate) SetCreatedAt(v time.Time) *UsageLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCreatedAt(v *time.Time) *UsageLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UsageLogCreate) SetID(v int64) *UsageLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UsageLogMutation object of the builder.
func (_c *UsageLogCreate) Mutation() *UsageLogMutation {
	return _c.mutation
}

// Save creates the UsageLog in the database.
func (_c *UsageLogCreate) Save(ctx context.Context) (*UsageLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogCreate) SaveX(ctx context.Context) *UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := usagelog.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		v := usagelog.DefaultErrorType
		_c.mutation.SetErrorType(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := usagelog.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := usagelog.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := usagelog.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := usagelog.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.CacheReadTokens(); !ok {
		v := usagelog.DefaultCacheReadTokens
		_c.mutation.SetCacheReadTokens(v)
	}
	if _, ok := _c.mutation.CacheCreationTokens(); !ok {
		v := usagelog.DefaultCacheCreationTokens
		_c.mutation.SetCacheCreationTokens(v)
	}
	if _, ok := _c.mutation.CallCount(); !ok {
		v := usagelog.DefaultCallCount
		_c.mutation.SetCallCount(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := usagelog.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.RawCost(); !ok {
		v := usagelog.DefaultRawCost
		_c.mutation.SetRawCost(v)
	}
	if _, ok := _c.mutation.AboveHit(); !ok {
		v := usagelog.DefaultAboveHit
		_c.mutation.SetAboveHit(v)
	}
	if _, ok := _c.mutation.Overdraft(); !ok {
		v := usagelog.DefaultOverdraft
		_c.mutation.SetOverdraft(v)
	}
	if _, ok := _c.mutation.Billed(); !ok {
		v := usagelog.DefaultBilled
		_c.mutation.SetBilled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageLog.request_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageLog.model"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "UsageLog.format"`)}
	}
	if v, ok := _c.mutation.Format(); ok {
		if err := usagelog.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "UsageLog.format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		return &ValidationError{Name: "error_type", err: errors.New(`ent: missing required field "UsageLog.error_type"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "UsageLog.latency_ms"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "UsageLog.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "UsageLog.output_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "UsageLog.total_tokens"`)}
	}
	if _, ok := _c.mutation.CacheReadTokens(); !ok {
		return &ValidationError{Name: "cache_read_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_read_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreationTokens(); !ok {
		return &ValidationError{Name: "cache_creation_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_creation_tokens"`)}
	}
	if _, ok := _c.mutation.CallCount(); !ok {
		return &ValidationError{Name: "call_count", err: errors.New(`ent: missing required field "UsageLog.call_count"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "UsageLog.cost"`)}
	}
	if _, ok := _c.mutation.RawCost(); !ok {
		return &ValidationError{Name: "raw_cost", err: errors.New(`ent: missing required field "UsageLog.raw_cost"`)}
	}
	if _, ok := _c.mutation.AboveHit(); !ok {
		return &ValidationError{Name: "above_hit", err: errors.New(`ent: missing required field "UsageLog.above_hit"`)}
	}
	if _, ok := _c.mutation.Overdraft(); !ok {
		return &ValidationError{Name: "overdraft", err: errors.New(`ent: missing required field "UsageLog.overdraft"`)}
	}
	if _, ok := _c.mutation.Billed(); !ok {
		return &ValidationError{Name: "billed", err: errors.New(`ent: missing required field "UsageLog.billed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLog.created_at"`)}
	}
	return nil
}

func (_c *UsageLogCreate) sqlSave(ctx context.Context) (*UsageLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogCreate) createSpec() (*UsageLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelog.Table, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usagelog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(usagelog.FieldClientIP, field.TypeString, value)
		_node.ClientIP = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usagelog.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(usagelog.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(usagelog.FieldTemplateID, field.TypeInt64, value)
		_node.TemplateID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usagelog.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(usagelog.FieldKeyID, field.TypeInt64, value)
		_node.KeyID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.MappedModel(); ok {
		_spec.SetField(usagelog.FieldMappedModel, field.TypeString, value)
		_node.MappedModel = &value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(usagelog.FieldFormat, field.TypeEnum, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.ErrorType(); ok {
		_spec.SetField(usagelog.FieldErrorType, field.TypeString, value)
		_node.ErrorType = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(usagelog.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.TtftMs(); ok {
		_spec.SetField(usagelog.FieldTtftMs, field.TypeInt64, value)
		_node.TtftMs = &value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(usagelog.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.PriceInputMillis(); ok {
		_spec.SetField(usagelog.FieldPriceInputMillis, field.TypeInt64, value)
		_node.PriceInputMillis = &value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(usagelog.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.PriceOutputMillis(); ok {
		_spec.SetField(usagelog.FieldPriceOutputMillis, field.TypeInt64, value)
		_node.PriceOutputMillis = &value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(usagelog.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.CacheReadTokens(); ok {
		_spec.SetField(usagelog.FieldCacheReadTokens, field.TypeInt64, value)
		_node.CacheReadTokens = value
	}
	if value, ok := _c.mutation.PriceCacheReadMillis(); ok {
		_spec.SetField(usagelog.FieldPriceCacheReadMillis, field.TypeInt64, value)
		_node.PriceCacheReadMillis = &value
	}
	if value, ok := _c.mutation.CacheCreationTokens(); ok {
		_spec.SetField(usagelog.FieldCacheCreationTokens, field.TypeInt64, value)
		_node.CacheCreationTokens = value
	}
	if value, ok := _c.mutation.PriceCacheCreationMillis(); ok {
		_spec.SetField(usagelog.FieldPriceCacheCreationMillis, field.TypeInt64, value)
		_node.PriceCacheCreationMillis = &value
	}
	if value, ok := _c.mutation.CallCount(); ok {
		_spec.SetField(usagelog.FieldCallCount, field.TypeInt64, value)
		_node.CallCount = value
	}
	if value, ok := _c.mutation.PricePerCallMillis(); ok {
		_spec.SetField(usagelog.FieldPricePerCallMillis, field.TypeInt64, value)
		_node.PricePerCallMillis = &value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(usagelog.FieldCost, field.TypeInt64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.RawCost(); ok {
		_spec.SetField(usagelog.FieldRawCost, field.TypeInt64, value)
		_node.RawCost = value
	}
	if value, ok := _c.mutation.BillingTier(); ok {
		_spec.SetField(usagelog.FieldBillingTier, field.TypeString, value)
		_node.BillingTier = &value
	}
	if value, ok := _c.mutation.AboveHit(); ok {
		_spec.SetField(usagelog.FieldAboveHit, field.TypeBool, value)
		_node.AboveHit = value
	}
	if value, ok := _c.mutation.Overdraft(); ok {
		_spec.SetField(usagelog.FieldOverdraft, field.TypeBool, value)
		_node.Overdraft = value
	}
	if value, ok := _c.mutation.Billed(); ok {
		_spec.SetField(usagelog.FieldBilled, field.TypeBool, value)
		_node.Billed = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLog.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogCreate) OnConflict(opts ...sql.ConflictOption) *UsageLogUpsertOne {
	_c.conflict = opts
	return &UsageLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogCreate) OnConflictColumns(columns ...string) *UsageLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogUpsertOne{
		create: _c,
	}
}

type (
	// UsageLogUpsertOne is the builder for "upsert"-ing
	//  one UsageLog node.
	UsageLogUpsertOne struct {
		create *UsageLogCreate
	}

	// UsageLogUpsert is the "OnConflict" setter.
	UsageLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsert) SetRequestID(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateRequestID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldRequestID)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *UsageLogUpsert) SetClientIP(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateClientIP() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldClientIP)
	return u
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *UsageLogUpsert) ClearClientIP() *UsageLogUpsert {
	u.SetNull(usagelog.FieldClientIP)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsert) SetGroupID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateGroupID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UsageLogUpsert) AddGroupID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsert) ClearGroupID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsert) SetAccountID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateAccountID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageLogUpsert) AddAccountID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageLogUpsert) ClearAccountID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldAccountID)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *UsageLogUpsert) SetTemplateID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateTemplateID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldTemplateID)
	return u
}

// AddTemplateID adds v to the "template_id" field.
func (u *UsageLogUpsert) AddTemplateID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldTemplateID, v)
	return u
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *UsageLogUpsert) ClearTemplateID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldTemplateID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UsageLogUpsert) SetUserID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateUserID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UsageLogUpsert) AddUserID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *UsageLogUpsert) ClearUserID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldUserID)
	return u
}

// SetKeyID sets the "key_id" field.
func (u *UsageLogUpsert) SetKeyID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldKeyID, v)
	return u
}

// UpdateKeyID sets the "key_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateKeyID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldKeyID)
	return u
}

// AddKeyID adds v to the "key_id" field.
func (u *UsageLogUpsert) AddKeyID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldKeyID, v)
	return u
}

// ClearKeyID clears the value of the "key_id" field.
func (u *UsageLogUpsert) ClearKeyID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldKeyID)
	return u
}

// SetModel sets the "model" field.
func (u *UsageLogUpsert) SetModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldModel)
	return u
}

// SetMappedModel sets the "mapped_model" field.
func (u *UsageLogUpsert) SetMappedModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldMappedModel, v)
	return u
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateMappedModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldMappedModel)
	return u
}

// ClearMappedModel clears the value of the "mapped_model" field.
func (u *UsageLogUpsert) ClearMappedModel() *UsageLogUpsert {
	u.SetNull(usagelog.FieldMappedModel)
	return u
}

// SetFormat sets the "format" field.
func (u *UsageLogUpsert) SetFormat(v usagelog.Format) *UsageLogUpsert {
	u.Set(usagelog.FieldFormat, v)
	return u
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateFormat() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldFormat)
	return u
}

// SetErrorType sets the "error_type" field.
func (u *UsageLogUpsert) SetErrorType(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldErrorType, v)
	return u
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateErrorType() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldErrorType)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *UsageLogUpsert) SetLatencyMs(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateLatencyMs() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *UsageLogUpsert) AddLatencyMs(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldLatencyMs, v)
	return u
}

// SetTtftMs sets the "ttft_ms" field.
func (u *UsageLogUpsert) SetTtftMs(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldTtftMs, v)
	return u
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateTtftMs() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldTtftMs)
	return u
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *UsageLogUpsert) AddTtftMs(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldTtftMs, v)
	return u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *UsageLogUpsert) ClearTtftMs() *UsageLogUpsert {
	u.SetNull(usagelog.FieldTtftMs)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *UsageLogUpsert) SetInputTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateInputTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *UsageLogUpsert) AddInputTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldInputTokens, v)
	return u
}

// SetPriceInputMillis sets the "price_input_millis" field.
func (u *UsageLogUpsert) SetPriceInputMillis(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldPriceInputMillis, v)
	return u
}

// UpdatePriceInputMillis sets the "price_input_millis" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdatePriceInputMillis() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldPriceInputMillis)
	return u
}

// AddPriceInputMillis adds v to the "price_input_millis" field.
func (u *UsageLogUpsert) AddPriceInputMillis(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldPriceInputMillis, v)
	return u
}

// ClearPriceInputMillis clears the value of the "price_input_millis" field.
func (u *UsageLogUpsert) ClearPriceInputMillis() *UsageLogUpsert {
	u.SetNull(usagelog.FieldPriceInputMillis)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *UsageLogUpsert) SetOutputTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateOutputTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *UsageLogUpsert) AddOutputTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldOutputTokens, v)
	return u
}

// SetPriceOutputMillis sets the "price_output_millis" field.
func (u *UsageLogUpsert) SetPriceOutputMillis(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldPriceOutputMillis, v)
	return u
}

// UpdatePriceOutputMillis sets the "price_output_millis" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdatePriceOutputMillis() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldPriceOutputMillis)
	return u
}

// AddPriceOutputMillis adds v to the "price_output_millis" field.
func (u *UsageLogUpsert) AddPriceOutputMillis(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldPriceOutputMillis, v)
	return u
}

// ClearPriceOutputMillis clears the value of the "price_output_millis" field.
func (u *UsageLogUpsert) ClearPriceOutputMillis() *UsageLogUpsert {
	u.SetNull(usagelog.FieldPriceOutputMillis)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageLogUpsert) SetTotalTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateTotalTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageLogUpsert) AddTotalTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldTotalTokens, v)
	return u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *UsageLogUpsert) SetCacheReadTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldCacheReadTokens, v)
	return u
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCacheReadTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCacheReadTokens)
	return u
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *UsageLogUpsert) AddCacheReadTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldCacheReadTokens, v)
	return u
}

// SetPriceCacheReadMillis sets the "price_cache_read_millis" field.
func (u *UsageLogUpsert) SetPriceCacheReadMillis(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldPriceCacheReadMillis, v)
	return u
}

// UpdatePriceCacheReadMillis sets the "price_cache_read_millis" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdatePriceCacheReadMillis() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldPriceCacheReadMillis)
	return u
}

// AddPriceCacheReadMillis adds v to the "price_cache_read_millis" field.
func (u *UsageLogUpsert) AddPriceCacheReadMillis(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldPriceCacheReadMillis, v)
	return u
}

// ClearPriceCacheReadMillis clears the value of the "price_cache_read_millis" field.
func (u *UsageLogUpsert) ClearPriceCacheReadMillis() *UsageLogUpsert {
	u.SetNull(usagelog.FieldPriceCacheReadMillis)
	return u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *UsageLogUpsert) SetCacheCreationTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldCacheCreationTokens, v)
	return u
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCacheCreationTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCacheCreationTokens)
	return u
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *UsageLogUpsert) AddCacheCreationTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldCacheCreationTokens, v)
	return u
}

// SetPriceCacheCreationMillis sets the "price_cache_creation_millis" field.
func (u *UsageLogUpsert) SetPriceCacheCreationMillis(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldPriceCacheCreationMillis, v)
	return u
}

// UpdatePriceCacheCreationMillis sets the "price_cache_creation_millis" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdatePriceCacheCreationMillis() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldPriceCacheCreationMillis)
	return u
}

// AddPriceCacheCreationMillis adds v to the "price_cache_creation_millis" field.
func (u *UsageLogUpsert) AddPriceCacheCreationMillis(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldPriceCacheCreationMillis, v)
	return u
}

// ClearPriceCacheCreationMillis clears the value of the "price_cache_creation_millis" field.
func (u *UsageLogUpsert) ClearPriceCacheCreationMillis() *UsageLogUpsert {
	u.SetNull(usagelog.FieldPriceCacheCreationMillis)
	return u
}

// SetCallCount sets the "call_count" field.
func (u *UsageLogUpsert) SetCallCount(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldCallCount, v)
	return u
}

// UpdateCallCount sets the "call_count" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCallCount() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCallCount)
	return u
}

// AddCallCount adds v to the "call_count" field.
func (u *UsageLogUpsert) AddCallCount(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldCallCount, v)
	return u
}

// SetPricePerCallMillis sets the "price_per_call_millis" field.
func (u *UsageLogUpsert) SetPricePerCallMillis(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldPricePerCallMillis, v)
	return u
}

// UpdatePricePerCallMillis sets the "price_per_call_millis" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdatePricePerCallMillis() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldPricePerCallMillis)
	return u
}

// AddPricePerCallMillis adds v to the "price_per_call_millis" field.
func (u *UsageLogUpsert) AddPricePerCallMillis(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldPricePerCallMillis, v)
	return u
}

// ClearPricePerCallMillis clears the value of the "price_per_call_millis" field.
func (u *UsageLogUpsert) ClearPricePerCallMillis() *UsageLogUpsert {
	u.SetNull(usagelog.FieldPricePerCallMillis)
	return u
}

// SetCost sets the "cost" field.
func (u *UsageLogUpsert) SetCost(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCost() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *UsageLogUpsert) AddCost(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldCost, v)
	return u
}

// SetRawCost sets the "raw_cost" field.
func (u *UsageLogUpsert) SetRawCost(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldRawCost, v)
	return u
}

// UpdateRawCost sets the "raw_cost" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateRawCost() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldRawCost)
	return u
}

// AddRawCost adds v to the "raw_cost" field.
func (u *UsageLogUpsert) AddRawCost(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldRawCost, v)
	return u
}

// SetBillingTier sets the "billing_tier" field.
func (u *UsageLogUpsert) SetBillingTier(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldBillingTier, v)
	return u
}

// UpdateBillingTier sets the "billing_tier" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateBillingTier() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldBillingTier)
	return u
}

// ClearBillingTier clears the value of the "billing_tier" field.
func (u *UsageLogUpsert) ClearBillingTier() *UsageLogUpsert {
	u.SetNull(usagelog.FieldBillingTier)
	return u
}

// SetAboveHit sets the "above_hit" field.
func (u *UsageLogUpsert) SetAboveHit(v bool) *UsageLogUpsert {
	u.Set(usagelog.FieldAboveHit, v)
	return u
}

// UpdateAboveHit sets the "above_hit" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateAboveHit() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldAboveHit)
	return u
}

// SetOverdraft sets the "overdraft" field.
func (u *UsageLogUpsert) SetOverdraft(v bool) *UsageLogUpsert {
	u.Set(usagelog.FieldOverdraft, v)
	return u
}

// UpdateOverdraft sets the "overdraft" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateOverdraft() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldOverdraft)
	return u
}

// SetBilled sets the "billed" field.
func (u *UsageLogUpsert) SetBilled(v bool) *UsageLogUpsert {
	u.Set(usagelog.FieldBilled, v)
	return u
}

// UpdateBilled sets the "billed" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateBilled() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldBilled)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UsageLogUpsert) SetCreatedAt(v time.Time) *UsageLogUpsert {
	u.Set(usagelog.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCreatedAt() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usagelog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UsageLogUpsertOne) UpdateNewValues() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(usagelog.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageLogUpsertOne) Ignore() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogUpsertOne) DoNothing() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogCreate.OnConflict
// documentation for more info.
func (u *UsageLogUpsertOne) Update(set func(*UsageLogUpsert)) *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsertOne) SetRequestID(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateRequestID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *UsageLogUpsertOne) SetClientIP(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateClientIP() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *UsageLogUpsertOne) ClearClientIP() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearClientIP()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsertOne) SetGroupID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UsageLogUpsertOne) AddGroupID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateGroupID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsertOne) ClearGroupID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsertOne) SetAccountID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageLogUpsertOne) AddAccountID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateAccountID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageLogUpsertOne) ClearAccountID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearAccountID()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *UsageLogUpsertOne) SetTemplateID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *UsageLogUpsertOne) AddTemplateID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateTemplateID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *UsageLogUpsertOne) ClearTemplateID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearTemplateID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UsageLogUpsertOne) SetUserID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UsageLogUpsertOne) AddUserID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateUserID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *UsageLogUpsertOne) ClearUserID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUserID()
	})
}

// SetKeyID sets the "key_id" field.
func (u *UsageLogUpsertOne) SetKeyID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetKeyID(v)
	})
}

// AddKeyID adds v to the "key_id" field.
func (u *UsageLogUpsertOne) AddKeyID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddKeyID(v)
	})
}

// UpdateKeyID sets the "key_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateKeyID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateKeyID()
	})
}

// ClearKeyID clears the value of the "key_id" field.
func (u *UsageLogUpsertOne) ClearKeyID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearKeyID()
	})
}

// SetModel sets the "model" field.
func (u *UsageLogUpsertOne) SetModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModel()
	})
}

// SetMappedModel sets the "mapped_model" field.
func (u *UsageLogUpsertOne) SetMappedModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetMappedModel(v)
	})
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateMappedModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateMappedModel()
	})
}

// ClearMappedModel clears the value of the "mapped_model" field.
func (u *UsageLogUpsertOne) ClearMappedModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearMappedModel()
	})
}

// SetFormat sets the "format" field.
func (u *UsageLogUpsertOne) SetFormat(v usagelog.Format) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateFormat() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateFormat()
	})
}

// SetErrorType sets the "error_type" field.
func (u *UsageLogUpsertOne) SetErrorType(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateErrorType() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateErrorType()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *UsageLogUpsertOne) SetLatencyMs(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *UsageLogUpsertOne) AddLatencyMs(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateLatencyMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *UsageLogUpsertOne) SetTtftMs(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *UsageLogUpsertOne) AddTtftMs(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateTtftMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTtftMs()
	})
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *UsageLogUpsertOne) ClearTtftMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearTtftMs()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *UsageLogUpsertOne) SetInputTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *UsageLogUpsertOne) AddInputTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateInputTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetPriceInputMillis sets the "price_input_millis" field.
func (u *UsageLogUpsertOne) SetPriceInputMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceInputMillis(v)
	})
}

// AddPriceInputMillis adds v to the "price_input_millis" field.
func (u *UsageLogUpsertOne) AddPriceInputMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceInputMillis(v)
	})
}

// UpdatePriceInputMillis sets the "price_input_millis" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdatePriceInputMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceInputMillis()
	})
}

// ClearPriceInputMillis clears the value of the "price_input_millis" field.
func (u *UsageLogUpsertOne) ClearPriceInputMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceInputMillis()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *UsageLogUpsertOne) SetOutputTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *UsageLogUpsertOne) AddOutputTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateOutputTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetPriceOutputMillis sets the "price_output_millis" field.
func (u *UsageLogUpsertOne) SetPriceOutputMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceOutputMillis(v)
	})
}

// AddPriceOutputMillis adds v to the "price_output_millis" field.
func (u *UsageLogUpsertOne) AddPriceOutputMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceOutputMillis(v)
	})
}

// UpdatePriceOutputMillis sets the "price_output_millis" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdatePriceOutputMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceOutputMillis()
	})
}

// ClearPriceOutputMillis clears the value of the "price_output_millis" field.
func (u *UsageLogUpsertOne) ClearPriceOutputMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceOutputMillis()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageLogUpsertOne) SetTotalTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageLogUpsertOne) AddTotalTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateTotalTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *UsageLogUpsertOne) SetCacheReadTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheReadTokens(v)
	})
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *UsageLogUpsertOne) AddCacheReadTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheReadTokens(v)
	})
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCacheReadTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheReadTokens()
	})
}

// SetPriceCacheReadMillis sets the "price_cache_read_millis" field.
func (u *UsageLogUpsertOne) SetPriceCacheReadMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceCacheReadMillis(v)
	})
}

// AddPriceCacheReadMillis adds v to the "price_cache_read_millis" field.
func (u *UsageLogUpsertOne) AddPriceCacheReadMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceCacheReadMillis(v)
	})
}

// UpdatePriceCacheReadMillis sets the "price_cache_read_millis" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdatePriceCacheReadMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceCacheReadMillis()
	})
}

// ClearPriceCacheReadMillis clears the value of the "price_cache_read_millis" field.
func (u *UsageLogUpsertOne) ClearPriceCacheReadMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceCacheReadMillis()
	})
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *UsageLogUpsertOne) SetCacheCreationTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreationTokens(v)
	})
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *UsageLogUpsertOne) AddCacheCreationTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreationTokens(v)
	})
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCacheCreationTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreationTokens()
	})
}

// SetPriceCacheCreationMillis sets the "price_cache_creation_millis" field.
func (u *UsageLogUpsertOne) SetPriceCacheCreationMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceCacheCreationMillis(v)
	})
}

// AddPriceCacheCreationMillis adds v to the "price_cache_creation_millis" field.
func (u *UsageLogUpsertOne) AddPriceCacheCreationMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceCacheCreationMillis(v)
	})
}

// UpdatePriceCacheCreationMillis sets the "price_cache_creation_millis" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdatePriceCacheCreationMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceCacheCreationMillis()
	})
}

// ClearPriceCacheCreationMillis clears the value of the "price_cache_creation_millis" field.
func (u *UsageLogUpsertOne) ClearPriceCacheCreationMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceCacheCreationMillis()
	})
}

// SetCallCount sets the "call_count" field.
func (u *UsageLogUpsertOne) SetCallCount(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCallCount(v)
	})
}

// AddCallCount adds v to the "call_count" field.
func (u *UsageLogUpsertOne) AddCallCount(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCallCount(v)
	})
}

// UpdateCallCount sets the "call_count" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCallCount() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCallCount()
	})
}

// SetPricePerCallMillis sets the "price_per_call_millis" field.
func (u *UsageLogUpsertOne) SetPricePerCallMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPricePerCallMillis(v)
	})
}

// AddPricePerCallMillis adds v to the "price_per_call_millis" field.
func (u *UsageLogUpsertOne) AddPricePerCallMillis(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPricePerCallMillis(v)
	})
}

// UpdatePricePerCallMillis sets the "price_per_call_millis" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdatePricePerCallMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePricePerCallMillis()
	})
}

// ClearPricePerCallMillis clears the value of the "price_per_call_millis" field.
func (u *UsageLogUpsertOne) ClearPricePerCallMillis() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPricePerCallMillis()
	})
}

// SetCost sets the "cost" field.
func (u *UsageLogUpsertOne) SetCost(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *UsageLogUpsertOne) AddCost(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCost() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCost()
	})
}

// SetRawCost sets the "raw_cost" field.
func (u *UsageLogUpsertOne) SetRawCost(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRawCost(v)
	})
}

// AddRawCost adds v to the "raw_cost" field.
func (u *UsageLogUpsertOne) AddRawCost(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddRawCost(v)
	})
}

// UpdateRawCost sets the "raw_cost" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateRawCost() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRawCost()
	})
}

// SetBillingTier sets the "billing_tier" field.
func (u *UsageLogUpsertOne) SetBillingTier(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetBillingTier(v)
	})
}

// UpdateBillingTier sets the "billing_tier" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateBillingTier() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateBillingTier()
	})
}

// ClearBillingTier clears the value of the "billing_tier" field.
func (u *UsageLogUpsertOne) ClearBillingTier() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearBillingTier()
	})
}

// SetAboveHit sets the "above_hit" field.
func (u *UsageLogUpsertOne) SetAboveHit(v bool) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAboveHit(v)
	})
}

// UpdateAboveHit sets the "above_hit" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateAboveHit() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAboveHit()
	})
}

// SetOverdraft sets the "overdraft" field.
func (u *UsageLogUpsertOne) SetOverdraft(v bool) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetOverdraft(v)
	})
}

// UpdateOverdraft sets the "overdraft" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateOverdraft() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateOverdraft()
	})
}

// SetBilled sets the "billed" field.
func (u *UsageLogUpsertOne) SetBilled(v bool) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetBilled(v)
	})
}

// UpdateBilled sets the "billed" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateBilled() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateBilled()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UsageLogUpsertOne) SetCreatedAt(v time.Time) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCreatedAt() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UsageLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageLogCreateBulk is the builder for creating many UsageLog entities in bulk.
type UsageLogCreateBulk struct {
	config
	err      error
	builders []*UsageLogCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageLog entities in the database.
func (_c *UsageLogCreateBulk) Save(ctx context.Context) ([]*UsageLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogCreateBulk) SaveX(ctx context.Context) []*UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageLogUpsertBulk {
	_c.conflict = opts
	return &UsageLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogCreateBulk) OnConflictColumns(columns ...string) *UsageLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogUpsertBulk{
		create: _c,
	}
}

// UsageLogUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageLog nodes.
type UsageLogUpsertBulk struct {
	create *UsageLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usagelog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UsageLogUpsertBulk) UpdateNewValues() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(usagelog.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageLogUpsertBulk) Ignore() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogUpsertBulk) DoNothing() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogCreateBulk.OnConflict
// documentation for more info.
func (u *UsageLogUpsertBulk) Update(set func(*UsageLogUpsert)) *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsertBulk) SetRequestID(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateRequestID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *UsageLogUpsertBulk) SetClientIP(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateClientIP() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *UsageLogUpsertBulk) ClearClientIP() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearClientIP()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsertBulk) SetGroupID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UsageLogUpsertBulk) AddGroupID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateGroupID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsertBulk) ClearGroupID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsertBulk) SetAccountID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageLogUpsertBulk) AddAccountID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateAccountID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageLogUpsertBulk) ClearAccountID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearAccountID()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *UsageLogUpsertBulk) SetTemplateID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *UsageLogUpsertBulk) AddTemplateID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateTemplateID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *UsageLogUpsertBulk) ClearTemplateID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearTemplateID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UsageLogUpsertBulk) SetUserID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UsageLogUpsertBulk) AddUserID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateUserID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *UsageLogUpsertBulk) ClearUserID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUserID()
	})
}

// SetKeyID sets the "key_id" field.
func (u *UsageLogUpsertBulk) SetKeyID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetKeyID(v)
	})
}

// AddKeyID adds v to the "key_id" field.
func (u *UsageLogUpsertBulk) AddKeyID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddKeyID(v)
	})
}

// UpdateKeyID sets the "key_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateKeyID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateKeyID()
	})
}

// ClearKeyID clears the value of the "key_id" field.
func (u *UsageLogUpsertBulk) ClearKeyID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearKeyID()
	})
}

// SetModel sets the "model" field.
func (u *UsageLogUpsertBulk) SetModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModel()
	})
}

// SetMappedModel sets the "mapped_model" field.
func (u *UsageLogUpsertBulk) SetMappedModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetMappedModel(v)
	})
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateMappedModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateMappedModel()
	})
}

// ClearMappedModel clears the value of the "mapped_model" field.
func (u *UsageLogUpsertBulk) ClearMappedModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearMappedModel()
	})
}

// SetFormat sets the "format" field.
func (u *UsageLogUpsertBulk) SetFormat(v usagelog.Format) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateFormat() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateFormat()
	})
}

// SetErrorType sets the "error_type" field.
func (u *UsageLogUpsertBulk) SetErrorType(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateErrorType() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateErrorType()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *UsageLogUpsertBulk) SetLatencyMs(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *UsageLogUpsertBulk) AddLatencyMs(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateLatencyMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *UsageLogUpsertBulk) SetTtftMs(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *UsageLogUpsertBulk) AddTtftMs(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateTtftMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTtftMs()
	})
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *UsageLogUpsertBulk) ClearTtftMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearTtftMs()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *UsageLogUpsertBulk) SetInputTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *UsageLogUpsertBulk) AddInputTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateInputTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetPriceInputMillis sets the "price_input_millis" field.
func (u *UsageLogUpsertBulk) SetPriceInputMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceInputMillis(v)
	})
}

// AddPriceInputMillis adds v to the "price_input_millis" field.
func (u *UsageLogUpsertBulk) AddPriceInputMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceInputMillis(v)
	})
}

// UpdatePriceInputMillis sets the "price_input_millis" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdatePriceInputMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceInputMillis()
	})
}

// ClearPriceInputMillis clears the value of the "price_input_millis" field.
func (u *UsageLogUpsertBulk) ClearPriceInputMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceInputMillis()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *UsageLogUpsertBulk) SetOutputTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *UsageLogUpsertBulk) AddOutputTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateOutputTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetPriceOutputMillis sets the "price_output_millis" field.
func (u *UsageLogUpsertBulk) SetPriceOutputMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceOutputMillis(v)
	})
}

// AddPriceOutputMillis adds v to the "price_output_millis" field.
func (u *UsageLogUpsertBulk) AddPriceOutputMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceOutputMillis(v)
	})
}

// UpdatePriceOutputMillis sets the "price_output_millis" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdatePriceOutputMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceOutputMillis()
	})
}

// ClearPriceOutputMillis clears the value of the "price_output_millis" field.
func (u *UsageLogUpsertBulk) ClearPriceOutputMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceOutputMillis()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageLogUpsertBulk) SetTotalTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageLogUpsertBulk) AddTotalTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateTotalTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *UsageLogUpsertBulk) SetCacheReadTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheReadTokens(v)
	})
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *UsageLogUpsertBulk) AddCacheReadTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheReadTokens(v)
	})
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCacheReadTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheReadTokens()
	})
}

// SetPriceCacheReadMillis sets the "price_cache_read_millis" field.
func (u *UsageLogUpsertBulk) SetPriceCacheReadMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceCacheReadMillis(v)
	})
}

// AddPriceCacheReadMillis adds v to the "price_cache_read_millis" field.
func (u *UsageLogUpsertBulk) AddPriceCacheReadMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceCacheReadMillis(v)
	})
}

// UpdatePriceCacheReadMillis sets the "price_cache_read_millis" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdatePriceCacheReadMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceCacheReadMillis()
	})
}

// ClearPriceCacheReadMillis clears the value of the "price_cache_read_millis" field.
func (u *UsageLogUpsertBulk) ClearPriceCacheReadMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceCacheReadMillis()
	})
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *UsageLogUpsertBulk) SetCacheCreationTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreationTokens(v)
	})
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *UsageLogUpsertBulk) AddCacheCreationTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreationTokens(v)
	})
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCacheCreationTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreationTokens()
	})
}

// SetPriceCacheCreationMillis sets the "price_cache_creation_millis" field.
func (u *UsageLogUpsertBulk) SetPriceCacheCreationMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPriceCacheCreationMillis(v)
	})
}

// AddPriceCacheCreationMillis adds v to the "price_cache_creation_millis" field.
func (u *UsageLogUpsertBulk) AddPriceCacheCreationMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPriceCacheCreationMillis(v)
	})
}

// UpdatePriceCacheCreationMillis sets the "price_cache_creation_millis" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdatePriceCacheCreationMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePriceCacheCreationMillis()
	})
}

// ClearPriceCacheCreationMillis clears the value of the "price_cache_creation_millis" field.
func (u *UsageLogUpsertBulk) ClearPriceCacheCreationMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPriceCacheCreationMillis()
	})
}

// SetCallCount sets the "call_count" field.
func (u *UsageLogUpsertBulk) SetCallCount(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCallCount(v)
	})
}

// AddCallCount adds v to the "call_count" field.
func (u *UsageLogUpsertBulk) AddCallCount(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCallCount(v)
	})
}

// UpdateCallCount sets the "call_count" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCallCount() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCallCount()
	})
}

// SetPricePerCallMillis sets the "price_per_call_millis" field.
func (u *UsageLogUpsertBulk) SetPricePerCallMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPricePerCallMillis(v)
	})
}

// AddPricePerCallMillis adds v to the "price_per_call_millis" field.
func (u *UsageLogUpsertBulk) AddPricePerCallMillis(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPricePerCallMillis(v)
	})
}

// UpdatePricePerCallMillis sets the "price_per_call_millis" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdatePricePerCallMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePricePerCallMillis()
	})
}

// ClearPricePerCallMillis clears the value of the "price_per_call_millis" field.
func (u *UsageLogUpsertBulk) ClearPricePerCallMillis() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearPricePerCallMillis()
	})
}

// SetCost sets the "cost" field.
func (u *UsageLogUpsertBulk) SetCost(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *UsageLogUpsertBulk) AddCost(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCost() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCost()
	})
}

// SetRawCost sets the "raw_cost" field.
func (u *UsageLogUpsertBulk) SetRawCost(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRawCost(v)
	})
}

// AddRawCost adds v to the "raw_cost" field.
func (u *UsageLogUpsertBulk) AddRawCost(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddRawCost(v)
	})
}

// UpdateRawCost sets the "raw_cost" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateRawCost() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRawCost()
	})
}

// SetBillingTier sets the "billing_tier" field.
func (u *UsageLogUpsertBulk) SetBillingTier(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetBillingTier(v)
	})
}

// UpdateBillingTier sets the "billing_tier" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateBillingTier() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateBillingTier()
	})
}

// ClearBillingTier clears the value of the "billing_tier" field.
func (u *UsageLogUpsertBulk) ClearBillingTier() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearBillingTier()
	})
}

// SetAboveHit sets the "above_hit" field.
func (u *UsageLogUpsertBulk) SetAboveHit(v bool) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAboveHit(v)
	})
}

// UpdateAboveHit sets the "above_hit" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateAboveHit() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAboveHit()
	})
}

// SetOverdraft sets the "overdraft" field.
func (u *UsageLogUpsertBulk) SetOverdraft(v bool) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetOverdraft(v)
	})
}

// UpdateOverdraft sets the "overdraft" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateOverdraft() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateOverdraft()
	})
}

// SetBilled sets the "billed" field.
func (u *UsageLogUpsertBulk) SetBilled(v bool) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetBilled(v)
	})
}

// UpdateBilled sets the "billed" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateBilled() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateBilled()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UsageLogUpsertBulk) SetCreatedAt(v time.Time) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCreatedAt() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UsageLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
