// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/predicate"
	"github.com/is7qin/c3api/internal/ent/usageentitystat"
)

// UsageEntityStatUpdate is the builder for updating UsageEntityStat entities.
type UsageEntityStatUpdate struct {
	config
	hooks    []Hook
	mutation *UsageEntityStatMutation
}

// Where appends a list predicates to the UsageEntityStatUpdate builder.
func (_u *UsageEntityStatUpdate) Where(ps ...predicate.UsageEntityStat) *UsageEntityStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBucketTime sets the "bucket_time" field.
func (_u *UsageEntityStatUpdate) SetBucketTime(v time.Time) *UsageEntityStatUpdate {
	_u.mutation.SetBucketTime(v)
	return _u
}

// SetNillableBucketTime sets the "bucket_time" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableBucketTime(v *time.Time) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetBucketTime(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *UsageEntityStatUpdate) SetEntityType(v string) *UsageEntityStatUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableEntityType(v *string) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *UsageEntityStatUpdate) SetEntityID(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableEntityID(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *UsageEntityStatUpdate) AddEntityID(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddEntityID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *UsageEntityStatUpdate) SetModel(v string) *UsageEntityStatUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableModel(v *string) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageEntityStatUpdate) SetRequestCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableRequestCount(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageEntityStatUpdate) AddRequestCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *UsageEntityStatUpdate) SetErrorCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableErrorCount(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *UsageEntityStatUpdate) AddErrorCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetCallCount sets the "call_count" field.
func (_u *UsageEntityStatUpdate) SetCallCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetCallCount()
	_u.mutation.SetCallCount(v)
	return _u
}

// SetNillableCallCount sets the "call_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableCallCount(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetCallCount(*v)
	}
	return _u
}

// AddCallCount adds value to the "call_count" field.
func (_u *UsageEntityStatUpdate) AddCallCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddCallCount(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *UsageEntityStatUpdate) SetInputTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableInputTokens(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *UsageEntityStatUpdate) AddInputTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *UsageEntityStatUpdate) SetOutputTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableOutputTokens(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *UsageEntityStatUpdate) AddOutputTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *UsageEntityStatUpdate) SetTotalTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableTotalTokens(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *UsageEntityStatUpdate) AddTotalTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *UsageEntityStatUpdate) SetCacheReadTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableCacheReadTokens(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *UsageEntityStatUpdate) AddCacheReadTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *UsageEntityStatUpdate) SetCacheCreationTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableCacheCreationTokens(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *UsageEntityStatUpdate) AddCacheCreationTokens(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *UsageEntityStatUpdate) SetCost(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableCost(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *UsageEntityStatUpdate) AddCost(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetRawCost sets the "raw_cost" field.
func (_u *UsageEntityStatUpdate) SetRawCost(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetRawCost()
	_u.mutation.SetRawCost(v)
	return _u
}

// SetNillableRawCost sets the "raw_cost" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableRawCost(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetRawCost(*v)
	}
	return _u
}

// AddRawCost adds value to the "raw_cost" field.
func (_u *UsageEntityStatUpdate) AddRawCost(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddRawCost(v)
	return _u
}

// SetTtftTotalMs sets the "ttft_total_ms" field.
func (_u *UsageEntityStatUpdate) SetTtftTotalMs(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetTtftTotalMs()
	_u.mutation.SetTtftTotalMs(v)
	return _u
}

// SetNillableTtftTotalMs sets the "ttft_total_ms" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableTtftTotalMs(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetTtftTotalMs(*v)
	}
	return _u
}

// AddTtftTotalMs adds value to the "ttft_total_ms" field.
func (_u *UsageEntityStatUpdate) AddTtftTotalMs(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddTtftTotalMs(v)
	return _u
}

// SetTtftCount sets the "ttft_count" field.
func (_u *UsageEntityStatUpdate) SetTtftCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetTtftCount()
	_u.mutation.SetTtftCount(v)
	return _u
}

// SetNillableTtftCount sets the "ttft_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableTtftCount(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetTtftCount(*v)
	}
	return _u
}

// AddTtftCount adds value to the "ttft_count" field.
func (_u *UsageEntityStatUpdate) AddTtftCount(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddTtftCount(v)
	return _u
}

// SetTtftMaxMs sets the "ttft_max_ms" field.
func (_u *UsageEntityStatUpdate) SetTtftMaxMs(v int64) *UsageEntityStatUpdate {
	_u.mutation.ResetTtftMaxMs()
	_u.mutation.SetTtftMaxMs(v)
	return _u
}

// SetNillableTtftMaxMs sets the "ttft_max_ms" field if the given value is not nil.
func (_u *UsageEntityStatUpdate) SetNillableTtftMaxMs(v *int64) *UsageEntityStatUpdate {
	if v != nil {
		_u.SetTtftMaxMs(*v)
	}
	return _u
}

// AddTtftMaxMs adds value to the "ttft_max_ms" field.
func (_u *UsageEntityStatUpdate) AddTtftMaxMs(v int64) *UsageEntityStatUpdate {
	_u.mutation.AddTtftMaxMs(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageEntityStatUpdate) SetUpdatedAt(v time.Time) *UsageEntityStatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UsageEntityStatMutation object of the builder.
func (_u *UsageEntityStatUpdate) Mutation() *UsageEntityStatMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageEntityStatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageEntityStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageEntityStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageEntityStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageEntityStatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usageentitystat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UsageEntityStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usageentitystat.Table, usageentitystat.Columns, sqlgraph.NewFieldSpec(usageentitystat.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketTime(); ok {
		_spec.SetField(usageentitystat.FieldBucketTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(usageentitystat.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(usageentitystat.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(usageentitystat.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(usageentitystat.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usageentitystat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usageentitystat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(usageentitystat.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(usageentitystat.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CallCount(); ok {
		_spec.SetField(usageentitystat.FieldCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCallCount(); ok {
		_spec.AddField(usageentitystat.FieldCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(usageentitystat.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(usageentitystat.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(usageentitystat.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usageentitystat.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(usageentitystat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(usageentitystat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(usageentitystat.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(usageentitystat.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(usageentitystat.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(usageentitystat.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(usageentitystat.FieldCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(usageentitystat.FieldCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RawCost(); ok {
		_spec.SetField(usageentitystat.FieldRawCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRawCost(); ok {
		_spec.AddField(usageentitystat.FieldRawCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftTotalMs(); ok {
		_spec.SetField(usageentitystat.FieldTtftTotalMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftTotalMs(); ok {
		_spec.AddField(usageentitystat.FieldTtftTotalMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftCount(); ok {
		_spec.SetField(usageentitystat.FieldTtftCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftCount(); ok {
		_spec.AddField(usageentitystat.FieldTtftCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftMaxMs(); ok {
		_spec.SetField(usageentitystat.FieldTtftMaxMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftMaxMs(); ok {
		_spec.AddField(usageentitystat.FieldTtftMaxMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usageentitystat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usageentitystat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageEntityStatUpdateOne is the builder for updating a single UsageEntityStat entity.
type UsageEntityStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageEntityStatMutation
}

// SetBucketTime sets the "bucket_time" field.
func (_u *UsageEntityStatUpdateOne) SetBucketTime(v time.Time) *UsageEntityStatUpdateOne {
	_u.mutation.SetBucketTime(v)
	return _u
}

// SetNillableBucketTime sets the "bucket_time" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableBucketTime(v *time.Time) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetBucketTime(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *UsageEntityStatUpdateOne) SetEntityType(v string) *UsageEntityStatUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableEntityType(v *string) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *UsageEntityStatUpdateOne) SetEntityID(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableEntityID(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *UsageEntityStatUpdateOne) AddEntityID(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddEntityID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *UsageEntityStatUpdateOne) SetModel(v string) *UsageEntityStatUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableModel(v *string) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageEntityStatUpdateOne) SetRequestCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableRequestCount(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageEntityStatUpdateOne) AddRequestCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *UsageEntityStatUpdateOne) SetErrorCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableErrorCount(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *UsageEntityStatUpdateOne) AddErrorCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetCallCount sets the "call_count" field.
func (_u *UsageEntityStatUpdateOne) SetCallCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetCallCount()
	_u.mutation.SetCallCount(v)
	return _u
}

// SetNillableCallCount sets the "call_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableCallCount(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetCallCount(*v)
	}
	return _u
}

// AddCallCount adds value to the "call_count" field.
func (_u *UsageEntityStatUpdateOne) AddCallCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddCallCount(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *UsageEntityStatUpdateOne) SetInputTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableInputTokens(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *UsageEntityStatUpdateOne) AddInputTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *UsageEntityStatUpdateOne) SetOutputTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableOutputTokens(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *UsageEntityStatUpdateOne) AddOutputTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *UsageEntityStatUpdateOne) SetTotalTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableTotalTokens(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *UsageEntityStatUpdateOne) AddTotalTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *UsageEntityStatUpdateOne) SetCacheReadTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableCacheReadTokens(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *UsageEntityStatUpdateOne) AddCacheReadTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *UsageEntityStatUpdateOne) SetCacheCreationTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableCacheCreationTokens(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *UsageEntityStatUpdateOne) AddCacheCreationTokens(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *UsageEntityStatUpdateOne) SetCost(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableCost(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *UsageEntityStatUpdateOne) AddCost(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetRawCost sets the "raw_cost" field.
func (_u *UsageEntityStatUpdateOne) SetRawCost(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetRawCost()
	_u.mutation.SetRawCost(v)
	return _u
}

// SetNillableRawCost sets the "raw_cost" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableRawCost(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetRawCost(*v)
	}
	return _u
}

// AddRawCost adds value to the "raw_cost" field.
func (_u *UsageEntityStatUpdateOne) AddRawCost(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddRawCost(v)
	return _u
}

// SetTtftTotalMs sets the "ttft_total_ms" field.
func (_u *UsageEntityStatUpdateOne) SetTtftTotalMs(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetTtftTotalMs()
	_u.mutation.SetTtftTotalMs(v)
	return _u
}

// SetNillableTtftTotalMs sets the "ttft_total_ms" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableTtftTotalMs(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetTtftTotalMs(*v)
	}
	return _u
}

// AddTtftTotalMs adds value to the "ttft_total_ms" field.
func (_u *UsageEntityStatUpdateOne) AddTtftTotalMs(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddTtftTotalMs(v)
	return _u
}

// SetTtftCount sets the "ttft_count" field.
func (_u *UsageEntityStatUpdateOne) SetTtftCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetTtftCount()
	_u.mutation.SetTtftCount(v)
	return _u
}

// SetNillableTtftCount sets the "ttft_count" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableTtftCount(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetTtftCount(*v)
	}
	return _u
}

// AddTtftCount adds value to the "ttft_count" field.
func (_u *UsageEntityStatUpdateOne) AddTtftCount(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddTtftCount(v)
	return _u
}

// SetTtftMaxMs sets the "ttft_max_ms" field.
func (_u *UsageEntityStatUpdateOne) SetTtftMaxMs(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.ResetTtftMaxMs()
	_u.mutation.SetTtftMaxMs(v)
	return _u
}

// SetNillableTtftMaxMs sets the "ttft_max_ms" field if the given value is not nil.
func (_u *UsageEntityStatUpdateOne) SetNillableTtftMaxMs(v *int64) *UsageEntityStatUpdateOne {
	if v != nil {
		_u.SetTtftMaxMs(*v)
	}
	return _u
}

// AddTtftMaxMs adds value to the "ttft_max_ms" field.
func (_u *UsageEntityStatUpdateOne) AddTtftMaxMs(v int64) *UsageEntityStatUpdateOne {
	_u.mutation.AddTtftMaxMs(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageEntityStatUpdateOne) SetUpdatedAt(v time.Time) *UsageEntityStatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UsageEntityStatMutation object of the builder.
func (_u *UsageEntityStatUpdateOne) Mutation() *UsageEntityStatMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageEntityStatUpdate builder.
func (_u *UsageEntityStatUpdateOne) Where(ps ...predicate.UsageEntityStat) *UsageEntityStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageEntityStatUpdateOne) Select(field string, fields ...string) *UsageEntityStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageEntityStat entity.
func (_u *UsageEntityStatUpdateOne) Save(ctx context.Context) (*UsageEntityStat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageEntityStatUpdateOne) SaveX(ctx context.Context) *UsageEntityStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageEntityStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageEntityStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageEntityStatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usageentitystat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UsageEntityStatUpdateOne) sqlSave(ctx context.Context) (_node *UsageEntityStat, err error) {
	_spec := sqlgraph.NewUpdateSpec(usageentitystat.Table, usageentitystat.Columns, sqlgraph.NewFieldSpec(usageentitystat.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageEntityStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usageentitystat.FieldID)
		for _, f := range fields {
			if !usageentitystat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usageentitystat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketTime(); ok {
		_spec.SetField(usageentitystat.FieldBucketTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(usageentitystat.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(usageentitystat.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(usageentitystat.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(usageentitystat.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usageentitystat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usageentitystat.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(usageentitystat.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(usageentitystat.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CallCount(); ok {
		_spec.SetField(usageentitystat.FieldCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCallCount(); ok {
		_spec.AddField(usageentitystat.FieldCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(usageentitystat.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(usageentitystat.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(usageentitystat.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usageentitystat.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(usageentitystat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(usageentitystat.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(usageentitystat.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(usageentitystat.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(usageentitystat.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(usageentitystat.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(usageentitystat.FieldCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(usageentitystat.FieldCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RawCost(); ok {
		_spec.SetField(usageentitystat.FieldRawCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRawCost(); ok {
		_spec.AddField(usageentitystat.FieldRawCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftTotalMs(); ok {
		_spec.SetField(usageentitystat.FieldTtftTotalMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftTotalMs(); ok {
		_spec.AddField(usageentitystat.FieldTtftTotalMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftCount(); ok {
		_spec.SetField(usageentitystat.FieldTtftCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftCount(); ok {
		_spec.AddField(usageentitystat.FieldTtftCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftMaxMs(); ok {
		_spec.SetField(usageentitystat.FieldTtftMaxMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftMaxMs(); ok {
		_spec.AddField(usageentitystat.FieldTtftMaxMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usageentitystat.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UsageEntityStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usageentitystat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
