// Package supplier provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package supplier

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseReason.
const (
	CubeHorizon     ErrorResponseReason = "cube_horizon"
	Dst             ErrorResponseReason = "dst"
	Offset          ErrorResponseReason = "offset"
	RawHorizon      ErrorResponseReason = "raw_horizon"
	SpanBelowGrid   ErrorResponseReason = "span_below_grid"
	WindowAmbiguous ErrorResponseReason = "window_ambiguous"
	WindowInvalid   ErrorResponseReason = "window_invalid"
	WindowTooLong   ErrorResponseReason = "window_too_long"
)

// Defines values for ErrorResponseStorage.
const (
	Cube ErrorResponseStorage = "cube"
	Raw  ErrorResponseStorage = "raw"
)

// Defines values for SupplierSettlementKind.
const (
	AdminRequest    SupplierSettlementKind = "admin_request"
	SupplierRequest SupplierSettlementKind = "supplier_request"
)

// Defines values for SupplierSettlementStatus.
const (
	Approved SupplierSettlementStatus = "approved"
	Paid     SupplierSettlementStatus = "paid"
	Paying   SupplierSettlementStatus = "paying"
	Pending  SupplierSettlementStatus = "pending"
	Rejected SupplierSettlementStatus = "rejected"
)

// ApplySettlementBody defines model for ApplySettlementBody.
type ApplySettlementBody struct {
	// AmountMillis 申请金额（> 0；受 available 条件扣约束）
	AmountMillis int64   `json:"amount_millis"`
	Note         *string `json:"note,omitempty"`

	// RequestKey 业务幂等键（客户端生成、重试复用；作用域 = 操作者 × key）
	RequestKey string `json:"request_key"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// EffectiveFrom 判定后的生效窗口下界（`window_invalid`/`window_ambiguous` 不携带）
	EffectiveFrom *time.Time `json:"effective_from,omitempty"`

	// EffectiveTo 判定后的生效窗口上界（`window_invalid`/`window_ambiguous` 不携带）
	EffectiveTo *time.Time `json:"effective_to,omitempty"`
	Error       string     `json:"error"`

	// LimitSeconds 成本上限秒数（`window_too_long` 携带；0 = 无上限）
	LimitSeconds *int64 `json:"limit_seconds,omitempty"`

	// Reason 统计窗口被拒的机读原因（仅统计端点可能携带）。取值词表取自规划层原因与
	// 拒绝原因的**全量映射表**（唯一来源），本版实际会发出的有五个：
	// raw_horizon/cube_horizon = 起点早于所要读表的保留截止；
	// window_too_long = 请求跨度超过该形状的成本上限；window_invalid =
	// 必填/倒序/`window` 时长串不可解析等参数本身非法；window_ambiguous =
	// `from`/`to`/`window` 三者的"恰择一"未被满足（两态都给、只给一端、
	// 或两态都不给）。offset/dst/span_below_grid 是"该窗口无法用卷积表精确
	// 表达、已降级到原始行"的派生原因（只用于降级告警日志，不作为拒绝原因
	// 发出）。
	Reason *ErrorResponseReason `json:"reason,omitempty"`

	// RetentionDays 覆盖判定所依据的最保守保留天数（`*_horizon` 携带）
	RetentionDays *int `json:"retention_days,omitempty"`

	// Storage 判定所依据的实际存储（`window_invalid`/`window_ambiguous` 不携带）
	Storage *ErrorResponseStorage `json:"storage,omitempty"`
}

// ErrorResponseReason 统计窗口被拒的机读原因（仅统计端点可能携带）。取值词表取自规划层原因与
// 拒绝原因的**全量映射表**（唯一来源），本版实际会发出的有五个：
// raw_horizon/cube_horizon = 起点早于所要读表的保留截止；
// window_too_long = 请求跨度超过该形状的成本上限；window_invalid =
// 必填/倒序/`window` 时长串不可解析等参数本身非法；window_ambiguous =
// `from`/`to`/`window` 三者的"恰择一"未被满足（两态都给、只给一端、
// 或两态都不给）。offset/dst/span_below_grid 是"该窗口无法用卷积表精确
// 表达、已降级到原始行"的派生原因（只用于降级告警日志，不作为拒绝原因
// 发出）。
type ErrorResponseReason string

// ErrorResponseStorage 判定所依据的实际存储（`window_invalid`/`window_ambiguous` 不携带）
type ErrorResponseStorage string

// SupplierChunk defines model for SupplierChunk.
type SupplierChunk struct {
	Amount      int64     `json:"amount"`
	AvailableAt time.Time `json:"available_at"`
}

// SupplierChunkList defines model for SupplierChunkList.
type SupplierChunkList struct {
	Items []SupplierChunk `json:"items"`
	Total int64           `json:"total"`
}

// SupplierEarning defines model for SupplierEarning.
type SupplierEarning struct {
	// Cost 计价额（毫分）
	Cost      int64     `json:"cost"`
	CreatedAt time.Time `json:"created_at"`

	// EarnMillis 收益额（毫分）
	EarnMillis int64   `json:"earn_millis"`
	Model      *string `json:"model,omitempty"`
}

// SupplierEarningList defines model for SupplierEarningList.
type SupplierEarningList struct {
	Items []SupplierEarning `json:"items"`
	Total int64             `json:"total"`
}

// SupplierOverview defines model for SupplierOverview.
type SupplierOverview struct {
	// Available 可提领（结算申请条件扣）
	Available int64 `json:"available"`

	// BucketRows 未解冻桶行数
	BucketRows int64 `json:"bucket_rows"`

	// FreezeHours 生效冻结小时（0 = 不冻结）
	FreezeHours int `json:"freeze_hours"`

	// FrozenAmount Σ 未解冻桶 amount
	FrozenAmount int64 `json:"frozen_amount"`

	// LatestAvailableAt 在途桶最晚解冻时刻（无桶 = null；运维可见性 §2.4）
	LatestAvailableAt *time.Time `json:"latest_available_at"`

	// LifetimeCredited 累计已入账（只增，永久）
	LifetimeCredited int64 `json:"lifetime_credited"`

	// LifetimePaid 累计已付（只增，永久）
	LifetimePaid int64 `json:"lifetime_paid"`

	// ShareBp 生效分成率（bp；10000 = 100%）
	ShareBp int `json:"share_bp"`
}

// SupplierSettlement defines model for SupplierSettlement.
type SupplierSettlement struct {
	AmountMillis         int64                    `json:"amount_millis"`
	ExternalRef          *string                  `json:"external_ref"`
	Id                   int64                    `json:"id"`
	Kind                 SupplierSettlementKind   `json:"kind"`
	Note                 *string                  `json:"note"`
	PaidAt               *time.Time               `json:"paid_at"`
	PaidOperatorUserId   *int64                   `json:"paid_operator_user_id"`
	PayoutFailedAt       *time.Time               `json:"payout_failed_at"`
	PayoutFailureReason  *string                  `json:"payout_failure_reason"`
	PayoutOperatorUserId *int64                   `json:"payout_operator_user_id"`
	PayoutStartedAt      *time.Time               `json:"payout_started_at"`
	PeriodEnd            time.Time                `json:"period_end"`
	PeriodStart          time.Time                `json:"period_start"`
	RejectReason         *string                  `json:"reject_reason"`
	RequestKey           string                   `json:"request_key"`
	RequestedAt          time.Time                `json:"requested_at"`
	RequestedOperator    int64                    `json:"requested_operator"`
	ReviewedAt           *time.Time               `json:"reviewed_at"`
	ReviewerUserId       *int64                   `json:"reviewer_user_id"`
	Revision             int64                    `json:"revision"`
	Status               SupplierSettlementStatus `json:"status"`
	SupplierUserId       int64                    `json:"supplier_user_id"`
}

// SupplierSettlementKind defines model for SupplierSettlement.Kind.
type SupplierSettlementKind string

// SupplierSettlementStatus defines model for SupplierSettlement.Status.
type SupplierSettlementStatus string

// SupplierSettlementList defines model for SupplierSettlementList.
type SupplierSettlementList struct {
	Items []SupplierSettlement `json:"items"`
	Total int64                `json:"total"`
}

// Error defines model for Error.
type Error = ErrorResponse

// GetSupplierChunksParams defines parameters for GetSupplierChunks.
type GetSupplierChunksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSupplierEarningsParams defines parameters for GetSupplierEarnings.
type GetSupplierEarningsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSupplierSettlementsParams defines parameters for GetSupplierSettlements.
type GetSupplierSettlementsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostSupplierSettlementJSONRequestBody defines body for PostSupplierSettlement for application/json ContentType.
type PostSupplierSettlementJSONRequestBody = ApplySettlementBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 冻结中明细（未解冻桶）
	// (GET /api/user/supplier/chunks)
	GetSupplierChunks(w http.ResponseWriter, r *http.Request, params GetSupplierChunksParams)
	// 区间收益明细（分页；走报表索引 ②，窗口 = 保留期）
	// (GET /api/user/supplier/earnings)
	GetSupplierEarnings(w http.ResponseWriter, r *http.Request, params GetSupplierEarningsParams)
	// 供应商收益概览（可提领/冻结/累计/生效分成率与冻结小时/最晚解冻时刻/桶行数）
	// (GET /api/user/supplier/overview)
	GetSupplierOverview(w http.ResponseWriter, r *http.Request)
	// 我的结算单（分页）
	// (GET /api/user/supplier/settlements)
	GetSupplierSettlements(w http.ResponseWriter, r *http.Request, params GetSupplierSettlementsParams)
	// 申请结算（条件扣 available + 期间链 + request_key 幂等）
	// (POST /api/user/supplier/settlements)
	PostSupplierSettlement(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 冻结中明细（未解冻桶）
// (GET /api/user/supplier/chunks)
func (_ Unimplemented) GetSupplierChunks(w http.ResponseWriter, r *http.Request, params GetSupplierChunksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 区间收益明细（分页；走报表索引 ②，窗口 = 保留期）
// (GET /api/user/supplier/earnings)
func (_ Unimplemented) GetSupplierEarnings(w http.ResponseWriter, r *http.Request, params GetSupplierEarningsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 供应商收益概览（可提领/冻结/累计/生效分成率与冻结小时/最晚解冻时刻/桶行数）
// (GET /api/user/supplier/overview)
func (_ Unimplemented) GetSupplierOverview(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的结算单（分页）
// (GET /api/user/supplier/settlements)
func (_ Unimplemented) GetSupplierSettlements(w http.ResponseWriter, r *http.Request, params GetSupplierSettlementsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 申请结算（条件扣 available + 期间链 + request_key 幂等）
// (POST /api/user/supplier/settlements)
func (_ Unimplemented) PostSupplierSettlement(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSupplierChunks operation middleware
func (siw *ServerInterfaceWrapper) GetSupplierChunks(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSupplierChunksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupplierChunks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupplierEarnings operation middleware
func (siw *ServerInterfaceWrapper) GetSupplierEarnings(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSupplierEarningsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupplierEarnings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupplierOverview operation middleware
func (siw *ServerInterfaceWrapper) GetSupplierOverview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupplierOverview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupplierSettlements operation middleware
func (siw *ServerInterfaceWrapper) GetSupplierSettlements(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSupplierSettlementsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupplierSettlements(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSupplierSettlement operation middleware
func (siw *ServerInterfaceWrapper) PostSupplierSettlement(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSupplierSettlement(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/supplier/chunks", wrapper.GetSupplierChunks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/supplier/earnings", wrapper.GetSupplierEarnings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/supplier/overview", wrapper.GetSupplierOverview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/supplier/settlements", wrapper.GetSupplierSettlements)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/supplier/settlements", wrapper.PostSupplierSettlement)
	})

	return r
}
