// Code generated by ent, DO NOT EDIT.

package usageentitystat

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usageentitystat type in the database.
	Label = "usage_entity_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBucketTime holds the string denoting the bucket_time field in the database.
	FieldBucketTime = "bucket_time"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldErrorCount holds the string denoting the error_count field in the database.
	FieldErrorCount = "error_count"
	// FieldCallCount holds the string denoting the call_count field in the database.
	FieldCallCount = "call_count"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldCacheCreationTokens holds the string denoting the cache_creation_tokens field in the database.
	FieldCacheCreationTokens = "cache_creation_tokens"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldRawCost holds the string denoting the raw_cost field in the database.
	FieldRawCost = "raw_cost"
	// FieldTtftTotalMs holds the string denoting the ttft_total_ms field in the database.
	FieldTtftTotalMs = "ttft_total_ms"
	// FieldTtftCount holds the string denoting the ttft_count field in the database.
	FieldTtftCount = "ttft_count"
	// FieldTtftMaxMs holds the string denoting the ttft_max_ms field in the database.
	FieldTtftMaxMs = "ttft_max_ms"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usageentitystat in the database.
	Table = "usage_entity_stats"
)

// Columns holds all SQL columns for usageentitystat fields.
var Columns = []string{
	FieldID,
	FieldBucketTime,
	FieldEntityType,
	FieldEntityID,
	FieldModel,
	FieldRequestCount,
	FieldErrorCount,
	FieldCallCount,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldCacheReadTokens,
	FieldCacheCreationTokens,
	FieldCost,
	FieldRawCost,
	FieldTtftTotalMs,
	FieldTtftCount,
	FieldTtftMaxMs,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int64
	// DefaultErrorCount holds the default value on creation for the "error_count" field.
	DefaultErrorCount int64
	// DefaultCallCount holds the default value on creation for the "call_count" field.
	DefaultCallCount int64
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int64
	// DefaultCacheCreationTokens holds the default value on creation for the "cache_creation_tokens" field.
	DefaultCacheCreationTokens int64
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost int64
	// DefaultRawCost holds the default value on creation for the "raw_cost" field.
	DefaultRawCost int64
	// DefaultTtftTotalMs holds the default value on creation for the "ttft_total_ms" field.
	DefaultTtftTotalMs int64
	// DefaultTtftCount holds the default value on creation for the "ttft_count" field.
	DefaultTtftCount int64
	// DefaultTtftMaxMs holds the default value on creation for the "ttft_max_ms" field.
	DefaultTtftMaxMs int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageEntityStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBucketTime orders the results by the bucket_time field.
func ByBucketTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketTime, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByErrorCount orders the results by the error_count field.
func ByErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCount, opts...).ToFunc()
}

// ByCallCount orders the results by the call_count field.
func ByCallCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallCount, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByCacheCreationTokens orders the results by the cache_creation_tokens field.
func ByCacheCreationTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationTokens, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByRawCost orders the results by the raw_cost field.
func ByRawCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawCost, opts...).ToFunc()
}

// ByTtftTotalMs orders the results by the ttft_total_ms field.
func ByTtftTotalMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtftTotalMs, opts...).ToFunc()
}

// ByTtftCount orders the results by the ttft_count field.
func ByTtftCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtftCount, opts...).ToFunc()
}

// ByTtftMaxMs orders the results by the ttft_max_ms field.
func ByTtftMaxMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtftMaxMs, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
