// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMaxConcurrency holds the string denoting the max_concurrency field in the database.
	FieldMaxConcurrency = "max_concurrency"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldTokenVersion holds the string denoting the token_version field in the database.
	FieldTokenVersion = "token_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeKeys holds the string denoting the keys edge name in mutations.
	EdgeKeys = "keys"
	// EdgeTempBalances holds the string denoting the temp_balances edge name in mutations.
	EdgeTempBalances = "temp_balances"
	// EdgeGroupAssignments holds the string denoting the group_assignments edge name in mutations.
	EdgeGroupAssignments = "group_assignments"
	// Table holds the table name of the user in the database.
	Table = "users"
	// KeysTable is the table that holds the keys relation/edge.
	KeysTable = "keys"
	// KeysInverseTable is the table name for the Key entity.
	// It exists in this package in order to avoid circular dependency with the "key" package.
	KeysInverseTable = "keys"
	// KeysColumn is the table column denoting the keys relation/edge.
	KeysColumn = "user_id"
	// TempBalancesTable is the table that holds the temp_balances relation/edge.
	TempBalancesTable = "temp_balances"
	// TempBalancesInverseTable is the table name for the TempBalance entity.
	// It exists in this package in order to avoid circular dependency with the "tempbalance" package.
	TempBalancesInverseTable = "temp_balances"
	// TempBalancesColumn is the table column denoting the temp_balances relation/edge.
	TempBalancesColumn = "user_id"
	// GroupAssignmentsTable is the table that holds the group_assignments relation/edge.
	GroupAssignmentsTable = "group_assignments"
	// GroupAssignmentsInverseTable is the table name for the GroupAssignment entity.
	// It exists in this package in order to avoid circular dependency with the "groupassignment" package.
	GroupAssignmentsInverseTable = "group_assignments"
	// GroupAssignmentsColumn is the table column denoting the group_assignments relation/edge.
	GroupAssignmentsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPasswordHash,
	FieldRole,
	FieldStatus,
	FieldMaxConcurrency,
	FieldBalance,
	FieldTokenVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMaxConcurrency holds the default value on creation for the "max_concurrency" field.
	DefaultMaxConcurrency int
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance int64
	// DefaultTokenVersion holds the default value on creation for the "token_version" field.
	DefaultTokenVersion int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Role defines the type for the "role" enum field.
type Role string

// RoleUser is the default value of the Role enum.
const DefaultRole = RoleUser

// Role values.
const (
	RolePlatformAdmin Role = "platform_admin"
	RoleUser          Role = "user"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RolePlatformAdmin, RoleUser:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMaxConcurrency orders the results by the max_concurrency field.
func ByMaxConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxConcurrency, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByTokenVersion orders the results by the token_version field.
func ByTokenVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKeysCount orders the results by keys count.
func ByKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newKeysStep(), opts...)
	}
}

// ByKeys orders the results by keys terms.
func ByKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTempBalancesCount orders the results by temp_balances count.
func ByTempBalancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTempBalancesStep(), opts...)
	}
}

// ByTempBalances orders the results by temp_balances terms.
func ByTempBalances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTempBalancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupAssignmentsCount orders the results by group_assignments count.
func ByGroupAssignmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupAssignmentsStep(), opts...)
	}
}

// ByGroupAssignments orders the results by group_assignments terms.
func ByGroupAssignments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupAssignmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, KeysTable, KeysColumn),
	)
}
func newTempBalancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TempBalancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TempBalancesTable, TempBalancesColumn),
	)
}
func newGroupAssignmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupAssignmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupAssignmentsTable, GroupAssignmentsColumn),
	)
}
