// Code generated by ent, DO NOT EDIT.

package accountext

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/is7qin/c3api/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldAccountID, v))
}

// CredentialType applies equality check predicate on the "credential_type" field. It's identical to CredentialTypeEQ.
func CredentialType(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldCredentialType, v))
}

// CodexAccountID applies equality check predicate on the "codex_account_id" field. It's identical to CodexAccountIDEQ.
func CodexAccountID(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldCodexAccountID, v))
}

// InstallationID applies equality check predicate on the "installation_id" field. It's identical to InstallationIDEQ.
func InstallationID(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldInstallationID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldSessionID, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldThreadID, v))
}

// WindowID applies equality check predicate on the "window_id" field. It's identical to WindowIDEQ.
func WindowID(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldWindowID, v))
}

// OauthToken applies equality check predicate on the "oauth_token" field. It's identical to OauthTokenEQ.
func OauthToken(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldOauthToken, v))
}

// OauthRefreshToken applies equality check predicate on the "oauth_refresh_token" field. It's identical to OauthRefreshTokenEQ.
func OauthRefreshToken(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldOauthRefreshToken, v))
}

// OauthExpiresAt applies equality check predicate on the "oauth_expires_at" field. It's identical to OauthExpiresAtEQ.
func OauthExpiresAt(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldOauthExpiresAt, v))
}

// PatKey applies equality check predicate on the "pat_key" field. It's identical to PatKeyEQ.
func PatKey(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldPatKey, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldEmail, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldAccountID, vs...))
}

// CredentialTypeEQ applies the EQ predicate on the "credential_type" field.
func CredentialTypeEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldCredentialType, v))
}

// CredentialTypeNEQ applies the NEQ predicate on the "credential_type" field.
func CredentialTypeNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldCredentialType, v))
}

// CredentialTypeIn applies the In predicate on the "credential_type" field.
func CredentialTypeIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldCredentialType, vs...))
}

// CredentialTypeNotIn applies the NotIn predicate on the "credential_type" field.
func CredentialTypeNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldCredentialType, vs...))
}

// CredentialTypeGT applies the GT predicate on the "credential_type" field.
func CredentialTypeGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldCredentialType, v))
}

// CredentialTypeGTE applies the GTE predicate on the "credential_type" field.
func CredentialTypeGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldCredentialType, v))
}

// CredentialTypeLT applies the LT predicate on the "credential_type" field.
func CredentialTypeLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldCredentialType, v))
}

// CredentialTypeLTE applies the LTE predicate on the "credential_type" field.
func CredentialTypeLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldCredentialType, v))
}

// CredentialTypeContains applies the Contains predicate on the "credential_type" field.
func CredentialTypeContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldCredentialType, v))
}

// CredentialTypeHasPrefix applies the HasPrefix predicate on the "credential_type" field.
func CredentialTypeHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldCredentialType, v))
}

// CredentialTypeHasSuffix applies the HasSuffix predicate on the "credential_type" field.
func CredentialTypeHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldCredentialType, v))
}

// CredentialTypeEqualFold applies the EqualFold predicate on the "credential_type" field.
func CredentialTypeEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldCredentialType, v))
}

// CredentialTypeContainsFold applies the ContainsFold predicate on the "credential_type" field.
func CredentialTypeContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldCredentialType, v))
}

// CodexAccountIDEQ applies the EQ predicate on the "codex_account_id" field.
func CodexAccountIDEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldCodexAccountID, v))
}

// CodexAccountIDNEQ applies the NEQ predicate on the "codex_account_id" field.
func CodexAccountIDNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldCodexAccountID, v))
}

// CodexAccountIDIn applies the In predicate on the "codex_account_id" field.
func CodexAccountIDIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldCodexAccountID, vs...))
}

// CodexAccountIDNotIn applies the NotIn predicate on the "codex_account_id" field.
func CodexAccountIDNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldCodexAccountID, vs...))
}

// CodexAccountIDGT applies the GT predicate on the "codex_account_id" field.
func CodexAccountIDGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldCodexAccountID, v))
}

// CodexAccountIDGTE applies the GTE predicate on the "codex_account_id" field.
func CodexAccountIDGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldCodexAccountID, v))
}

// CodexAccountIDLT applies the LT predicate on the "codex_account_id" field.
func CodexAccountIDLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldCodexAccountID, v))
}

// CodexAccountIDLTE applies the LTE predicate on the "codex_account_id" field.
func CodexAccountIDLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldCodexAccountID, v))
}

// CodexAccountIDContains applies the Contains predicate on the "codex_account_id" field.
func CodexAccountIDContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldCodexAccountID, v))
}

// CodexAccountIDHasPrefix applies the HasPrefix predicate on the "codex_account_id" field.
func CodexAccountIDHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldCodexAccountID, v))
}

// CodexAccountIDHasSuffix applies the HasSuffix predicate on the "codex_account_id" field.
func CodexAccountIDHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldCodexAccountID, v))
}

// CodexAccountIDIsNil applies the IsNil predicate on the "codex_account_id" field.
func CodexAccountIDIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldCodexAccountID))
}

// CodexAccountIDNotNil applies the NotNil predicate on the "codex_account_id" field.
func CodexAccountIDNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldCodexAccountID))
}

// CodexAccountIDEqualFold applies the EqualFold predicate on the "codex_account_id" field.
func CodexAccountIDEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldCodexAccountID, v))
}

// CodexAccountIDContainsFold applies the ContainsFold predicate on the "codex_account_id" field.
func CodexAccountIDContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldCodexAccountID, v))
}

// InstallationIDEQ applies the EQ predicate on the "installation_id" field.
func InstallationIDEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldInstallationID, v))
}

// InstallationIDNEQ applies the NEQ predicate on the "installation_id" field.
func InstallationIDNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldInstallationID, v))
}

// InstallationIDIn applies the In predicate on the "installation_id" field.
func InstallationIDIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldInstallationID, vs...))
}

// InstallationIDNotIn applies the NotIn predicate on the "installation_id" field.
func InstallationIDNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldInstallationID, vs...))
}

// InstallationIDGT applies the GT predicate on the "installation_id" field.
func InstallationIDGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldInstallationID, v))
}

// InstallationIDGTE applies the GTE predicate on the "installation_id" field.
func InstallationIDGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldInstallationID, v))
}

// InstallationIDLT applies the LT predicate on the "installation_id" field.
func InstallationIDLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldInstallationID, v))
}

// InstallationIDLTE applies the LTE predicate on the "installation_id" field.
func InstallationIDLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldInstallationID, v))
}

// InstallationIDContains applies the Contains predicate on the "installation_id" field.
func InstallationIDContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldInstallationID, v))
}

// InstallationIDHasPrefix applies the HasPrefix predicate on the "installation_id" field.
func InstallationIDHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldInstallationID, v))
}

// InstallationIDHasSuffix applies the HasSuffix predicate on the "installation_id" field.
func InstallationIDHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldInstallationID, v))
}

// InstallationIDEqualFold applies the EqualFold predicate on the "installation_id" field.
func InstallationIDEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldInstallationID, v))
}

// InstallationIDContainsFold applies the ContainsFold predicate on the "installation_id" field.
func InstallationIDContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldInstallationID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldSessionID, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDIsNil applies the IsNil predicate on the "thread_id" field.
func ThreadIDIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldThreadID))
}

// ThreadIDNotNil applies the NotNil predicate on the "thread_id" field.
func ThreadIDNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldThreadID))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldThreadID, v))
}

// WindowIDEQ applies the EQ predicate on the "window_id" field.
func WindowIDEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldWindowID, v))
}

// WindowIDNEQ applies the NEQ predicate on the "window_id" field.
func WindowIDNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldWindowID, v))
}

// WindowIDIn applies the In predicate on the "window_id" field.
func WindowIDIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldWindowID, vs...))
}

// WindowIDNotIn applies the NotIn predicate on the "window_id" field.
func WindowIDNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldWindowID, vs...))
}

// WindowIDGT applies the GT predicate on the "window_id" field.
func WindowIDGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldWindowID, v))
}

// WindowIDGTE applies the GTE predicate on the "window_id" field.
func WindowIDGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldWindowID, v))
}

// WindowIDLT applies the LT predicate on the "window_id" field.
func WindowIDLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldWindowID, v))
}

// WindowIDLTE applies the LTE predicate on the "window_id" field.
func WindowIDLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldWindowID, v))
}

// WindowIDContains applies the Contains predicate on the "window_id" field.
func WindowIDContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldWindowID, v))
}

// WindowIDHasPrefix applies the HasPrefix predicate on the "window_id" field.
func WindowIDHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldWindowID, v))
}

// WindowIDHasSuffix applies the HasSuffix predicate on the "window_id" field.
func WindowIDHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldWindowID, v))
}

// WindowIDIsNil applies the IsNil predicate on the "window_id" field.
func WindowIDIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldWindowID))
}

// WindowIDNotNil applies the NotNil predicate on the "window_id" field.
func WindowIDNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldWindowID))
}

// WindowIDEqualFold applies the EqualFold predicate on the "window_id" field.
func WindowIDEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldWindowID, v))
}

// WindowIDContainsFold applies the ContainsFold predicate on the "window_id" field.
func WindowIDContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldWindowID, v))
}

// OauthTokenEQ applies the EQ predicate on the "oauth_token" field.
func OauthTokenEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldOauthToken, v))
}

// OauthTokenNEQ applies the NEQ predicate on the "oauth_token" field.
func OauthTokenNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldOauthToken, v))
}

// OauthTokenIn applies the In predicate on the "oauth_token" field.
func OauthTokenIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldOauthToken, vs...))
}

// OauthTokenNotIn applies the NotIn predicate on the "oauth_token" field.
func OauthTokenNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldOauthToken, vs...))
}

// OauthTokenGT applies the GT predicate on the "oauth_token" field.
func OauthTokenGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldOauthToken, v))
}

// OauthTokenGTE applies the GTE predicate on the "oauth_token" field.
func OauthTokenGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldOauthToken, v))
}

// OauthTokenLT applies the LT predicate on the "oauth_token" field.
func OauthTokenLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldOauthToken, v))
}

// OauthTokenLTE applies the LTE predicate on the "oauth_token" field.
func OauthTokenLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldOauthToken, v))
}

// OauthTokenContains applies the Contains predicate on the "oauth_token" field.
func OauthTokenContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldOauthToken, v))
}

// OauthTokenHasPrefix applies the HasPrefix predicate on the "oauth_token" field.
func OauthTokenHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldOauthToken, v))
}

// OauthTokenHasSuffix applies the HasSuffix predicate on the "oauth_token" field.
func OauthTokenHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldOauthToken, v))
}

// OauthTokenIsNil applies the IsNil predicate on the "oauth_token" field.
func OauthTokenIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldOauthToken))
}

// OauthTokenNotNil applies the NotNil predicate on the "oauth_token" field.
func OauthTokenNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldOauthToken))
}

// OauthTokenEqualFold applies the EqualFold predicate on the "oauth_token" field.
func OauthTokenEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldOauthToken, v))
}

// OauthTokenContainsFold applies the ContainsFold predicate on the "oauth_token" field.
func OauthTokenContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldOauthToken, v))
}

// OauthRefreshTokenEQ applies the EQ predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenNEQ applies the NEQ predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenIn applies the In predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldOauthRefreshToken, vs...))
}

// OauthRefreshTokenNotIn applies the NotIn predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldOauthRefreshToken, vs...))
}

// OauthRefreshTokenGT applies the GT predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenGTE applies the GTE predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenLT applies the LT predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenLTE applies the LTE predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenContains applies the Contains predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenHasPrefix applies the HasPrefix predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenHasSuffix applies the HasSuffix predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenIsNil applies the IsNil predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldOauthRefreshToken))
}

// OauthRefreshTokenNotNil applies the NotNil predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldOauthRefreshToken))
}

// OauthRefreshTokenEqualFold applies the EqualFold predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldOauthRefreshToken, v))
}

// OauthRefreshTokenContainsFold applies the ContainsFold predicate on the "oauth_refresh_token" field.
func OauthRefreshTokenContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldOauthRefreshToken, v))
}

// OauthExpiresAtEQ applies the EQ predicate on the "oauth_expires_at" field.
func OauthExpiresAtEQ(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldOauthExpiresAt, v))
}

// OauthExpiresAtNEQ applies the NEQ predicate on the "oauth_expires_at" field.
func OauthExpiresAtNEQ(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldOauthExpiresAt, v))
}

// OauthExpiresAtIn applies the In predicate on the "oauth_expires_at" field.
func OauthExpiresAtIn(vs ...time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldOauthExpiresAt, vs...))
}

// OauthExpiresAtNotIn applies the NotIn predicate on the "oauth_expires_at" field.
func OauthExpiresAtNotIn(vs ...time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldOauthExpiresAt, vs...))
}

// OauthExpiresAtGT applies the GT predicate on the "oauth_expires_at" field.
func OauthExpiresAtGT(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldOauthExpiresAt, v))
}

// OauthExpiresAtGTE applies the GTE predicate on the "oauth_expires_at" field.
func OauthExpiresAtGTE(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldOauthExpiresAt, v))
}

// OauthExpiresAtLT applies the LT predicate on the "oauth_expires_at" field.
func OauthExpiresAtLT(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldOauthExpiresAt, v))
}

// OauthExpiresAtLTE applies the LTE predicate on the "oauth_expires_at" field.
func OauthExpiresAtLTE(v time.Time) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldOauthExpiresAt, v))
}

// OauthExpiresAtIsNil applies the IsNil predicate on the "oauth_expires_at" field.
func OauthExpiresAtIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldOauthExpiresAt))
}

// OauthExpiresAtNotNil applies the NotNil predicate on the "oauth_expires_at" field.
func OauthExpiresAtNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldOauthExpiresAt))
}

// PatKeyEQ applies the EQ predicate on the "pat_key" field.
func PatKeyEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldPatKey, v))
}

// PatKeyNEQ applies the NEQ predicate on the "pat_key" field.
func PatKeyNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldPatKey, v))
}

// PatKeyIn applies the In predicate on the "pat_key" field.
func PatKeyIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldPatKey, vs...))
}

// PatKeyNotIn applies the NotIn predicate on the "pat_key" field.
func PatKeyNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldPatKey, vs...))
}

// PatKeyGT applies the GT predicate on the "pat_key" field.
func PatKeyGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldPatKey, v))
}

// PatKeyGTE applies the GTE predicate on the "pat_key" field.
func PatKeyGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldPatKey, v))
}

// PatKeyLT applies the LT predicate on the "pat_key" field.
func PatKeyLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldPatKey, v))
}

// PatKeyLTE applies the LTE predicate on the "pat_key" field.
func PatKeyLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldPatKey, v))
}

// PatKeyContains applies the Contains predicate on the "pat_key" field.
func PatKeyContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldPatKey, v))
}

// PatKeyHasPrefix applies the HasPrefix predicate on the "pat_key" field.
func PatKeyHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldPatKey, v))
}

// PatKeyHasSuffix applies the HasSuffix predicate on the "pat_key" field.
func PatKeyHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldPatKey, v))
}

// PatKeyIsNil applies the IsNil predicate on the "pat_key" field.
func PatKeyIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldPatKey))
}

// PatKeyNotNil applies the NotNil predicate on the "pat_key" field.
func PatKeyNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldPatKey))
}

// PatKeyEqualFold applies the EqualFold predicate on the "pat_key" field.
func PatKeyEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldPatKey, v))
}

// PatKeyContainsFold applies the ContainsFold predicate on the "pat_key" field.
func PatKeyContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldPatKey, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.AccountExt {
	return predicate.AccountExt(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AccountExt {
	return predicate.AccountExt(sql.FieldContainsFold(FieldEmail, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountExt {
	return predicate.AccountExt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountExt {
	return predicate.AccountExt(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountExt) predicate.AccountExt {
	return predicate.AccountExt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountExt) predicate.AccountExt {
	return predicate.AccountExt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountExt) predicate.AccountExt {
	return predicate.AccountExt(sql.NotPredicates(p))
}
