// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package user

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorType.
const (
	Abort     ErrorType = "abort"
	Auth      ErrorType = "auth"
	Billing   ErrorType = "billing"
	N429      ErrorType = "429"
	N4xx      ErrorType = "4xx"
	N5xx      ErrorType = "5xx"
	Network   ErrorType = "network"
	NoAccount ErrorType = "no_account"
	None      ErrorType = "none"
)

// Defines values for GroupProtocolConvert.
const (
	ChatToMess GroupProtocolConvert = "chat_to_mess"
	ChatToResp GroupProtocolConvert = "chat_to_resp"
	MessToResp GroupProtocolConvert = "mess_to_resp"
	RespToMess GroupProtocolConvert = "resp_to_mess"
)

// Defines values for GroupVisibility.
const (
	Private GroupVisibility = "private"
	Public  GroupVisibility = "public"
)

// Defines values for KeyStatus.
const (
	KeyStatusActive   KeyStatus = "active"
	KeyStatusDisabled KeyStatus = "disabled"
)

// Defines values for RedemptionType.
const (
	Balance     RedemptionType = "balance"
	Concurrency RedemptionType = "concurrency"
	TempBalance RedemptionType = "temp_balance"
)

// Defines values for RequestFormat.
const (
	Anthropic         RequestFormat = "anthropic"
	OpenaiChat        RequestFormat = "openai-chat"
	OpenaiImages      RequestFormat = "openai-images"
	OpenaiResponses   RequestFormat = "openai-responses"
	OpenaiResponsesWs RequestFormat = "openai-responses-ws"
	OpenaiSearch      RequestFormat = "openai-search"
)

// Defines values for UserRole.
const (
	UserRolePlatformAdmin UserRole = "platform_admin"
	UserRoleUser          UserRole = "user"
)

// Defines values for UserStatus.
const (
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
)

// Defines values for GetUserKeysParamsOrder.
const (
	GetUserKeysParamsOrderAsc  GetUserKeysParamsOrder = "asc"
	GetUserKeysParamsOrderDesc GetUserKeysParamsOrder = "desc"
)

// Defines values for GetUserRedemptionsParamsOrder.
const (
	GetUserRedemptionsParamsOrderAsc  GetUserRedemptionsParamsOrder = "asc"
	GetUserRedemptionsParamsOrderDesc GetUserRedemptionsParamsOrder = "desc"
)

// Defines values for GetUserStatsParamsGranularity.
const (
	Day  GetUserStatsParamsGranularity = "day"
	Hour GetUserStatsParamsGranularity = "hour"
)

// ChangePasswordResponse defines model for ChangePasswordResponse.
type ChangePasswordResponse struct {
	Updated bool `json:"updated"`
}

// DeletedResponse defines model for DeletedResponse.
type DeletedResponse struct {
	Deleted bool `json:"deleted"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ErrorType defines model for ErrorType.
type ErrorType string

// Group defines model for Group.
type Group struct {
	CreatedAt *time.Time `json:"CreatedAt,omitempty"`

	// DeletedAt 软删除时间戳；null = 存活（列表/消费路径过滤已删；GET 单个可查已删项）
	DeletedAt *time.Time `json:"DeletedAt"`
	ID        *int64     `json:"ID,omitempty"`
	Name      *string    `json:"Name,omitempty"`

	// PriceMultiplier 价格倍率（正常值，1 = ×1，0 = 免费，上限 10 = ×10；API 边界与万分数换算——存储 15000 ↔ 显示 1.5）
	PriceMultiplier *float64 `json:"PriceMultiplier,omitempty"`

	// ProtocolConvert 协议转换方向集合（空数组 = off = 不转换；多方向按客户端格式命中）
	ProtocolConvert *[]GroupProtocolConvert `json:"ProtocolConvert,omitempty"`
	UpdatedAt       *time.Time              `json:"UpdatedAt,omitempty"`
	Visibility      *GroupVisibility        `json:"Visibility,omitempty"`
}

// GroupProtocolConvert 分组级协议转换方向（只补差，W5 网关 internal/protoconv 消费）：chat_to_resp = 客户端 chat → 模板 resp；mess_to_resp = anthropic messages → resp；resp_to_mess = resp → anthropic messages；chat_to_mess = chat → anthropic messages。off 不在枚举内——不转换 = 空数组（见 protocol_convert 字段说明）
type GroupProtocolConvert string

// GroupVisibility defines model for GroupVisibility.
type GroupVisibility string

// Key defines model for Key.
type Key struct {
	CreatedAt *time.Time `json:"CreatedAt,omitempty"`

	// DeletedAt 软删除时间戳；null = 存活（列表/鉴权过滤已删；GET 单个可查已删项）
	DeletedAt      *time.Time `json:"DeletedAt"`
	GroupID        *int64     `json:"GroupID,omitempty"`
	ID             *int64     `json:"ID,omitempty"`
	MaxConcurrency *int       `json:"MaxConcurrency,omitempty"`
	Name           *string    `json:"Name,omitempty"`

	// Quota 累计 token 上限；0 = 不限
	Quota *int64 `json:"Quota,omitempty"`

	// QuotaUsed 已消耗（后扣；无额度 key 恒 0）
	QuotaUsed *int64     `json:"QuotaUsed,omitempty"`
	Status    *KeyStatus `json:"Status,omitempty"`
	UpdatedAt *time.Time `json:"UpdatedAt,omitempty"`
	UserID    *int64     `json:"UserID,omitempty"`

	// Key key 明文（长期可查看/复制；DB 泄露即暴露——自托管权衡，用户裁决）
	Key *string `json:"key,omitempty"`
}

// KeyCreate defines model for KeyCreate.
type KeyCreate struct {
	GroupId int64 `json:"group_id"`

	// MaxConcurrency 单 key 在途上限；0 = 不限
	MaxConcurrency *int   `json:"max_concurrency,omitempty"`
	Name           string `json:"name"`

	// Quota 累计 token 上限；0 = 不限
	Quota *int64 `json:"quota,omitempty"`
}

// KeyListResponse defines model for KeyListResponse.
type KeyListResponse struct {
	Rows  []Key `json:"rows"`
	Total int64 `json:"total"`
}

// KeyStatus defines model for KeyStatus.
type KeyStatus string

// KeyUpdate defines model for KeyUpdate.
type KeyUpdate struct {
	MaxConcurrency *int       `json:"max_concurrency,omitempty"`
	Name           *string    `json:"name,omitempty"`
	Quota          *int64     `json:"quota,omitempty"`
	Status         *KeyStatus `json:"status,omitempty"`
}

// RedeemRequest defines model for RedeemRequest.
type RedeemRequest struct {
	Code string `json:"code"`
}

// RedeemResponse defines model for RedeemResponse.
type RedeemResponse struct {
	Applied struct {
		ResourceExpiresAt *time.Time     `json:"resource_expires_at"`
		Type              RedemptionType `json:"type"`

		// Value 兑换时的值快照（同面值单位语义）
		Value float64 `json:"value"`
	} `json:"applied"`
}

// RedemptionRecord defines model for RedemptionRecord.
type RedemptionRecord struct {
	Code              string         `json:"Code"`
	CodeID            int64          `json:"CodeID"`
	CodeType          RedemptionType `json:"CodeType"`
	CreatedAt         time.Time      `json:"CreatedAt"`
	ID                int64          `json:"ID"`
	Remark            *string        `json:"Remark"`
	ResourceExpiresAt *time.Time     `json:"ResourceExpiresAt"`

	// Value 兑换时的值快照（同面值单位语义）
	Value float64 `json:"Value"`
}

// RedemptionRecordListResponse defines model for RedemptionRecordListResponse.
type RedemptionRecordListResponse struct {
	Rows  []RedemptionRecord `json:"rows"`
	Total int64              `json:"total"`
}

// RedemptionType defines model for RedemptionType.
type RedemptionType string

// RequestFormat defines model for RequestFormat.
type RequestFormat string

// StatBucket 统计桶（rewrite spec 2026-08-14 契约更新：Cost 毫分 → USD /1e5 破坏性变更；TotalLatencyMS 随列删除；TTFT pN 服务端直方图插值——直方图不可前端反算）
type StatBucket struct {
	AccountID           *int64     `json:"AccountID,omitempty"`
	BucketTime          *time.Time `json:"BucketTime,omitempty"`
	CacheCreationTokens *int64     `json:"CacheCreationTokens,omitempty"`
	CacheReadTokens     *int64     `json:"CacheReadTokens,omitempty"`

	// CallCount 按次调用：图片生成张数、search 次数（不入 TotalTokens）
	CallCount *int64 `json:"CallCount,omitempty"`

	// Cost 成本 USD（毫分 /1e5，与价格 API/overview 口径一致；破坏性变更）
	Cost         *float64 `json:"Cost,omitempty"`
	ErrorCount   *int64   `json:"ErrorCount,omitempty"`
	GroupID      *int64   `json:"GroupID,omitempty"`
	InputTokens  *int64   `json:"InputTokens,omitempty"`
	IsError      *bool    `json:"IsError,omitempty"`
	Model        *string  `json:"Model,omitempty"`
	OutputTokens *int64   `json:"OutputTokens,omitempty"`
	RequestCount *int64   `json:"RequestCount,omitempty"`

	// TTFTAvgMS 首 token 平均毫秒（sum/count，无样本 = 0）
	TTFTAvgMS *float64 `json:"TTFTAvgMS,omitempty"`

	// TTFTCount 首 token 样本数（pN/加权 avg 分母——前端跨行合并必需）
	TTFTCount *int64 `json:"TTFTCount,omitempty"`

	// TTFTMaxMS 首 token 最大毫秒（无样本 = 0）
	TTFTMaxMS *int64 `json:"TTFTMaxMS,omitempty"`

	// TTFTP50MS 首 token 分位毫秒（直方图插值 nearest-rank + 桶内线性插值；顶桶 12800+ 回落 12800；无样本 = 0）
	TTFTP50MS *int64 `json:"TTFTP50MS,omitempty"`

	// TTFTP90MS 同 TTFTP50MS（p90）
	TTFTP90MS *int64 `json:"TTFTP90MS,omitempty"`

	// TTFTP95MS 同 TTFTP50MS（p95）
	TTFTP95MS *int64 `json:"TTFTP95MS,omitempty"`

	// TTFTP99MS 同 TTFTP50MS（p99）
	TTFTP99MS   *int64 `json:"TTFTP99MS,omitempty"`
	TemplateID  *int64 `json:"TemplateID,omitempty"`
	TotalTokens *int64 `json:"TotalTokens,omitempty"`

	// UserID 鉴权归属用户；0 = 无
	UserID *int64 `json:"UserID,omitempty"`

	// RawCostUsd 原始成本 USD（毫分 /1e5——乘倍率前"实际消耗"口径；免费组 cost 为 0 但 raw 有值）
	RawCostUsd *float64 `json:"raw_cost_usd,omitempty"`
}

// TempBalanceRow defines model for TempBalanceRow.
type TempBalanceRow struct {
	// AmountUsd 金额 USD（毫分 /1e5；1 USD = 100,000 毫分）
	AmountUsd float64 `json:"amount_usd"`

	// ExpiresAt 到期时间；null = 永久额度
	ExpiresAt *time.Time `json:"expires_at"`
	Id        int64      `json:"id"`

	// Note 固定系统备注（signup bonus / redemption code），无敏感信息
	Note *string `json:"note"`
}

// TempBalancesResponse defines model for TempBalancesResponse.
type TempBalancesResponse struct {
	Rows []TempBalanceRow `json:"rows"`

	// TotalUsd 有效额度合计 USD（毫分 Σ /1e5；0 = 无有效额度）
	TotalUsd float64 `json:"total_usd"`
}

// User defines model for User.
type User struct {
	// Balance 余额 USD（浮点；内部存储毫分——1 USD = 100,000 毫分，API 边界换算）
	Balance        *float64    `json:"Balance,omitempty"`
	CreatedAt      *time.Time  `json:"CreatedAt,omitempty"`
	Email          *string     `json:"Email,omitempty"`
	ID             *int64      `json:"ID,omitempty"`
	MaxConcurrency *int        `json:"MaxConcurrency,omitempty"`
	Role           *UserRole   `json:"Role,omitempty"`
	Status         *UserStatus `json:"Status,omitempty"`
	UpdatedAt      *time.Time  `json:"UpdatedAt,omitempty"`
}

// UserAuthChangePassword defines model for UserAuthChangePassword.
type UserAuthChangePassword struct {
	// NewPassword 非空且 ≤72 字节（bcrypt 截断限制），非法 400
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// UserAuthLogin defines model for UserAuthLogin.
type UserAuthLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UserAuthRegister defines model for UserAuthRegister.
type UserAuthRegister struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UserAuthResponse defines model for UserAuthResponse.
type UserAuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// UserErrLog 用户面错误明细（= ErrLog 删 AccountID/TemplateID——用户无上游账号拓扑概念）
type UserErrLog struct {
	// BillingTier 计费档位（service_tier 归一化：priority/flex/fast/auto）；null = 未计费路径
	BillingTier *string `json:"BillingTier"`

	// ClientIP 客户端 IP（CF-Connecting-IP / True-Client-IP / X-Real-IP 按序识别；无则 RemoteAddr 剥端口）；空 = 无
	ClientIP  *string    `json:"ClientIP,omitempty"`
	CreatedAt *time.Time `json:"CreatedAt,omitempty"`

	// ErrorMessage 错误文本（拒绝文案/上游 body，域内截断 500 字符）；null = 无错误文本
	ErrorMessage *string        `json:"ErrorMessage"`
	ErrorType    *ErrorType     `json:"ErrorType,omitempty"`
	Format       *RequestFormat `json:"Format,omitempty"`
	GroupID      *int64         `json:"GroupID,omitempty"`
	ID           *int64         `json:"ID,omitempty"`

	// KeyID 鉴权归属 key；0 = 无
	KeyID     *int64  `json:"KeyID,omitempty"`
	LatencyMS *int64  `json:"LatencyMS,omitempty"`
	Model     *string `json:"Model,omitempty"`
	RequestID *string `json:"RequestID,omitempty"`

	// StatusCode 错误状态码（完整错误面；0 = 连接级）
	StatusCode *int `json:"StatusCode,omitempty"`

	// UserID 鉴权归属用户；0 = 无
	UserID *int64 `json:"UserID,omitempty"`
}

// UserErrLogsResponse defines model for UserErrLogsResponse.
type UserErrLogsResponse struct {
	// NextCursor 下一页游标（本页最后一条 id）；null = 无更多行
	NextCursor *int64       `json:"next_cursor"`
	Rows       []UserErrLog `json:"rows"`
}

// UserLogsResponse defines model for UserLogsResponse.
type UserLogsResponse struct {
	// NextCursor 下一页游标（本页最后一条 id）；null = 无更多行
	NextCursor *int64         `json:"next_cursor"`
	Rows       []UserUsageLog `json:"rows"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserStatus defines model for UserStatus.
type UserStatus string

// UserUsageLog 用户面用量明细（= UsageLog 删 AccountID/TemplateID——用户无上游账号拓扑概念）
type UserUsageLog struct {
	// AboveHit 任一分量超 above 阈值命中分段
	AboveHit *bool `json:"AboveHit,omitempty"`

	// BillingTier 请求 service_tier 归一化值（priority/flex/fast/auto）；空 = 未计费路径
	BillingTier         *string `json:"BillingTier,omitempty"`
	CacheCreationTokens *int64  `json:"CacheCreationTokens,omitempty"`
	CacheReadTokens     *int64  `json:"CacheReadTokens,omitempty"`

	// ClientIP 客户端 IP（CF-Connecting-IP / True-Client-IP / X-Real-IP 按序识别；无则 RemoteAddr 剥端口）；空 = 无
	ClientIP *string `json:"ClientIP,omitempty"`

	// Cost 计费成本（毫分，1 USD = 100,000 毫分）；错误请求（402/4xx）为 0
	Cost        *int64         `json:"Cost,omitempty"`
	CreatedAt   *time.Time     `json:"CreatedAt,omitempty"`
	ErrorType   *ErrorType     `json:"ErrorType,omitempty"`
	Format      *RequestFormat `json:"Format,omitempty"`
	GroupID     *int64         `json:"GroupID,omitempty"`
	ID          *int64         `json:"ID,omitempty"`
	InputTokens *int64         `json:"InputTokens,omitempty"`

	// KeyID 鉴权归属 key；0 = 无
	KeyID        *int64  `json:"KeyID,omitempty"`
	LatencyMS    *int64  `json:"LatencyMS,omitempty"`
	MappedModel  *string `json:"MappedModel"`
	Model        *string `json:"Model,omitempty"`
	OutputTokens *int64  `json:"OutputTokens,omitempty"`

	// Overdraft 本次扣费透支（余额不足扣为负余额）
	Overdraft *bool `json:"Overdraft,omitempty"`

	// PriceCacheCreationMillis 缓存写单价快照（每 M token 毫分）；null = 该请求无缓存写或无缓存价
	PriceCacheCreationMillis *int64 `json:"PriceCacheCreationMillis"`

	// PriceCacheReadMillis 缓存读单价快照（每 M token 毫分）；null = 该请求无缓存读或无缓存价
	PriceCacheReadMillis *int64 `json:"PriceCacheReadMillis"`

	// PriceInputMillis 输入单价快照（每 M token 毫分，1 USD = 100,000 毫分；pricing 同款单位）；null = 未计费路径
	PriceInputMillis *int64 `json:"PriceInputMillis"`

	// PriceOutputMillis 输出单价快照（每 M token 毫分）；null = 未计费路径
	PriceOutputMillis *int64 `json:"PriceOutputMillis"`

	// RawCost 原始成本（毫分，乘倍率前——免费组 cost=0 但 raw 有值，实际消耗口径）；bill 未装配/无价防御路径恒 0
	RawCost   *int64  `json:"RawCost,omitempty"`
	RequestID *string `json:"RequestID,omitempty"`

	// TTFTMS 首 token 时间毫秒（流式首 chunk 采集）；非流式/失败/无首 token 路径 = null
	TTFTMS      *int64 `json:"TTFTMS"`
	TotalTokens *int64 `json:"TotalTokens,omitempty"`

	// UserID 鉴权归属用户；0 = 无
	UserID *int64 `json:"UserID,omitempty"`
}

// Error defines model for Error.
type Error = ErrorResponse

// GetUserErrLogsParams defines parameters for GetUserErrLogs.
type GetUserErrLogsParams struct {
	Limit      *int           `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor     *int64         `form:"cursor,omitempty" json:"cursor,omitempty"`
	GroupId    *int64         `form:"group_id,omitempty" json:"group_id,omitempty"`
	KeyId      *int64         `form:"key_id,omitempty" json:"key_id,omitempty"`
	Model      *string        `form:"model,omitempty" json:"model,omitempty"`
	Format     *RequestFormat `form:"format,omitempty" json:"format,omitempty"`
	StatusCode *int           `form:"status_code,omitempty" json:"status_code,omitempty"`
	ErrorType  *string        `form:"error_type,omitempty" json:"error_type,omitempty"`
	From       time.Time      `form:"from" json:"from"`
	To         time.Time      `form:"to" json:"to"`
}

// GetUserKeysParams defines parameters for GetUserKeys.
type GetUserKeysParams struct {
	Limit  *int                    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                    `form:"offset,omitempty" json:"offset,omitempty"`
	Name   *string                 `form:"name,omitempty" json:"name,omitempty"`
	Sort   *string                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *GetUserKeysParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetUserKeysParamsOrder defines parameters for GetUserKeys.
type GetUserKeysParamsOrder string

// GetUserRedemptionsParams defines parameters for GetUserRedemptions.
type GetUserRedemptionsParams struct {
	Page     *int                           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int                           `form:"page_size,omitempty" json:"page_size,omitempty"`
	Sort     *string                        `form:"sort,omitempty" json:"sort,omitempty"`
	Order    *GetUserRedemptionsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetUserRedemptionsParamsOrder defines parameters for GetUserRedemptions.
type GetUserRedemptionsParamsOrder string

// GetUserStatsParams defines parameters for GetUserStats.
type GetUserStatsParams struct {
	From        *time.Time                     `form:"from,omitempty" json:"from,omitempty"`
	To          *time.Time                     `form:"to,omitempty" json:"to,omitempty"`
	Granularity *GetUserStatsParamsGranularity `form:"granularity,omitempty" json:"granularity,omitempty"`
	GroupId     *int64                         `form:"group_id,omitempty" json:"group_id,omitempty"`
	AccountId   *int64                         `form:"account_id,omitempty" json:"account_id,omitempty"`
	TemplateId  *int64                         `form:"template_id,omitempty" json:"template_id,omitempty"`
	Model       *string                        `form:"model,omitempty" json:"model,omitempty"`
}

// GetUserStatsParamsGranularity defines parameters for GetUserStats.
type GetUserStatsParamsGranularity string

// GetUserUsageLogsParams defines parameters for GetUserUsageLogs.
type GetUserUsageLogsParams struct {
	Limit     *int           `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *int64         `form:"cursor,omitempty" json:"cursor,omitempty"`
	GroupId   *int64         `form:"group_id,omitempty" json:"group_id,omitempty"`
	KeyId     *int64         `form:"key_id,omitempty" json:"key_id,omitempty"`
	Model     *string        `form:"model,omitempty" json:"model,omitempty"`
	Format    *RequestFormat `form:"format,omitempty" json:"format,omitempty"`
	ErrorType *string        `form:"error_type,omitempty" json:"error_type,omitempty"`
	From      time.Time      `form:"from" json:"from"`
	To        time.Time      `form:"to" json:"to"`
}

// PostUserAuthChangePasswordJSONRequestBody defines body for PostUserAuthChangePassword for application/json ContentType.
type PostUserAuthChangePasswordJSONRequestBody = UserAuthChangePassword

// PostUserAuthLoginJSONRequestBody defines body for PostUserAuthLogin for application/json ContentType.
type PostUserAuthLoginJSONRequestBody = UserAuthLogin

// PostUserAuthRegisterJSONRequestBody defines body for PostUserAuthRegister for application/json ContentType.
type PostUserAuthRegisterJSONRequestBody = UserAuthRegister

// PostUserKeysJSONRequestBody defines body for PostUserKeys for application/json ContentType.
type PostUserKeysJSONRequestBody = KeyCreate

// PutUserKeysIdJSONRequestBody defines body for PutUserKeysId for application/json ContentType.
type PutUserKeysIdJSONRequestBody = KeyUpdate

// PostUserRedemptionsJSONRequestBody defines body for PostUserRedemptions for application/json ContentType.
type PostUserRedemptionsJSONRequestBody = RedeemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 修改密码（旧密码校验复用登录语义——失败 401 同登录文案防枚举；新密码非空且 ≤72 字节，非法 400；不撤销既有 JWT，新密码下次登录生效）
	// (POST /api/user/auth/change-password)
	PostUserAuthChangePassword(w http.ResponseWriter, r *http.Request)
	// 登录（bcrypt 校验 → JWT）
	// (POST /api/user/auth/login)
	PostUserAuthLogin(w http.ResponseWriter, r *http.Request)
	// 当前用户信息（JWT）
	// (GET /api/user/auth/me)
	GetUserAuthMe(w http.ResponseWriter, r *http.Request)
	// 注册（signup_enabled 开关检查；注册即登录返回 JWT）
	// (POST /api/user/auth/register)
	PostUserAuthRegister(w http.ResponseWriter, r *http.Request)
	// 我的错误明细（err_logs 完整错误面：拒绝 + 异常双轨；强制 user_id = 当前用户，防越权）
	// (GET /api/user/err_logs)
	GetUserErrLogs(w http.ResponseWriter, r *http.Request, params GetUserErrLogsParams)
	// 可选组列表（public 全部 + 已授予 private；只读，key 创建时选组）
	// (GET /api/user/groups)
	GetUserGroups(w http.ResponseWriter, r *http.Request)
	// 我的 key 列表（分页/排序；key 明文长期可查看/复制）
	// (GET /api/user/keys)
	GetUserKeys(w http.ResponseWriter, r *http.Request, params GetUserKeysParams)
	// 创建 key（组可选性校验：public 或已授予 private；明文长期回显）
	// (POST /api/user/keys)
	PostUserKeys(w http.ResponseWriter, r *http.Request)
	// 删除 key（仅本人；Auth 快照增量移除——立即失效）
	// (DELETE /api/user/keys/{id})
	DeleteUserKeysId(w http.ResponseWriter, r *http.Request, id int64)
	// key 详情（仅本人；他人 key → 404）
	// (GET /api/user/keys/{id})
	GetUserKeysId(w http.ResponseWriter, r *http.Request, id int64)
	// 更新 key（name/status/max_concurrency/quota；仅本人）
	// (PUT /api/user/keys/{id})
	PutUserKeysId(w http.ResponseWriter, r *http.Request, id int64)
	// 轮换 key（仅本人；新明文生效，旧 key 立即失效）
	// (POST /api/user/keys/{id}/rotate)
	PostUserKeysIdRotate(w http.ResponseWriter, r *http.Request, id int64)
	// 我的兑换记录（use 快照 + 码的 type/remark 联查；强制 user_id = 当前用户，防越权）
	// (GET /api/user/redemptions)
	GetUserRedemptions(w http.ResponseWriter, r *http.Request, params GetUserRedemptionsParams)
	// 兑换码（400 invalid code：不存在/失效/过期/用尽，统一不泄露细节；409 already redeemed 重复兑换）
	// (POST /api/user/redemptions)
	PostUserRedemptions(w http.ResponseWriter, r *http.Request)
	// 我的用量统计（强制 user_id = 当前用户）
	// (GET /api/user/stats)
	GetUserStats(w http.ResponseWriter, r *http.Request, params GetUserStatsParams)
	// 我的临时额度（仅有效额度：未过期且正余额，用尽/过期隐藏；expires_at 升序 FEFO 同序、永久最后；强制 user_id = 当前用户，无 user_id 参数防越权）
	// (GET /api/user/temp-balances)
	GetUserTempBalances(w http.ResponseWriter, r *http.Request)
	// 我的用量明细（usage_logs 纯计费明细；强制 user_id = 当前用户，防越权；error_type 值域 none/abort）
	// (GET /api/user/usage_logs)
	GetUserUsageLogs(w http.ResponseWriter, r *http.Request, params GetUserUsageLogsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 修改密码（旧密码校验复用登录语义——失败 401 同登录文案防枚举；新密码非空且 ≤72 字节，非法 400；不撤销既有 JWT，新密码下次登录生效）
// (POST /api/user/auth/change-password)
func (_ Unimplemented) PostUserAuthChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 登录（bcrypt 校验 → JWT）
// (POST /api/user/auth/login)
func (_ Unimplemented) PostUserAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 当前用户信息（JWT）
// (GET /api/user/auth/me)
func (_ Unimplemented) GetUserAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 注册（signup_enabled 开关检查；注册即登录返回 JWT）
// (POST /api/user/auth/register)
func (_ Unimplemented) PostUserAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的错误明细（err_logs 完整错误面：拒绝 + 异常双轨；强制 user_id = 当前用户，防越权）
// (GET /api/user/err_logs)
func (_ Unimplemented) GetUserErrLogs(w http.ResponseWriter, r *http.Request, params GetUserErrLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 可选组列表（public 全部 + 已授予 private；只读，key 创建时选组）
// (GET /api/user/groups)
func (_ Unimplemented) GetUserGroups(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的 key 列表（分页/排序；key 明文长期可查看/复制）
// (GET /api/user/keys)
func (_ Unimplemented) GetUserKeys(w http.ResponseWriter, r *http.Request, params GetUserKeysParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 创建 key（组可选性校验：public 或已授予 private；明文长期回显）
// (POST /api/user/keys)
func (_ Unimplemented) PostUserKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 删除 key（仅本人；Auth 快照增量移除——立即失效）
// (DELETE /api/user/keys/{id})
func (_ Unimplemented) DeleteUserKeysId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// key 详情（仅本人；他人 key → 404）
// (GET /api/user/keys/{id})
func (_ Unimplemented) GetUserKeysId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 更新 key（name/status/max_concurrency/quota；仅本人）
// (PUT /api/user/keys/{id})
func (_ Unimplemented) PutUserKeysId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 轮换 key（仅本人；新明文生效，旧 key 立即失效）
// (POST /api/user/keys/{id}/rotate)
func (_ Unimplemented) PostUserKeysIdRotate(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的兑换记录（use 快照 + 码的 type/remark 联查；强制 user_id = 当前用户，防越权）
// (GET /api/user/redemptions)
func (_ Unimplemented) GetUserRedemptions(w http.ResponseWriter, r *http.Request, params GetUserRedemptionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 兑换码（400 invalid code：不存在/失效/过期/用尽，统一不泄露细节；409 already redeemed 重复兑换）
// (POST /api/user/redemptions)
func (_ Unimplemented) PostUserRedemptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的用量统计（强制 user_id = 当前用户）
// (GET /api/user/stats)
func (_ Unimplemented) GetUserStats(w http.ResponseWriter, r *http.Request, params GetUserStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的临时额度（仅有效额度：未过期且正余额，用尽/过期隐藏；expires_at 升序 FEFO 同序、永久最后；强制 user_id = 当前用户，无 user_id 参数防越权）
// (GET /api/user/temp-balances)
func (_ Unimplemented) GetUserTempBalances(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的用量明细（usage_logs 纯计费明细；强制 user_id = 当前用户，防越权；error_type 值域 none/abort）
// (GET /api/user/usage_logs)
func (_ Unimplemented) GetUserUsageLogs(w http.ResponseWriter, r *http.Request, params GetUserUsageLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostUserAuthChangePassword operation middleware
func (siw *ServerInterfaceWrapper) PostUserAuthChangePassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserAuthChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostUserAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetUserAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUserAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserErrLogs operation middleware
func (siw *ServerInterfaceWrapper) GetUserErrLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserErrLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "key_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "key_id", r.URL.Query(), &params.KeyId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameter("form", true, false, "model", r.URL.Query(), &params.Model)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", r.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	// ------------- Optional query parameter "status_code" -------------

	err = runtime.BindQueryParameter("form", true, false, "status_code", r.URL.Query(), &params.StatusCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status_code", Err: err})
		return
	}

	// ------------- Optional query parameter "error_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_type", r.URL.Query(), &params.ErrorType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_type", Err: err})
		return
	}

	// ------------- Required query parameter "from" -------------

	if paramValue := r.URL.Query().Get("from"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := r.URL.Query().Get("to"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserErrLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserGroups operation middleware
func (siw *ServerInterfaceWrapper) GetUserGroups(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserKeys operation middleware
func (siw *ServerInterfaceWrapper) GetUserKeys(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserKeys operation middleware
func (siw *ServerInterfaceWrapper) PostUserKeys(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserKeysId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserKeysId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserKeysId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserKeysId operation middleware
func (siw *ServerInterfaceWrapper) GetUserKeysId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserKeysId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutUserKeysId operation middleware
func (siw *ServerInterfaceWrapper) PutUserKeysId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUserKeysId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserKeysIdRotate operation middleware
func (siw *ServerInterfaceWrapper) PostUserKeysIdRotate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserKeysIdRotate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserRedemptions operation middleware
func (siw *ServerInterfaceWrapper) GetUserRedemptions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserRedemptionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserRedemptions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRedemptions operation middleware
func (siw *ServerInterfaceWrapper) PostUserRedemptions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRedemptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserStats operation middleware
func (siw *ServerInterfaceWrapper) GetUserStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserStatsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameter("form", true, false, "granularity", r.URL.Query(), &params.Granularity)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_id", r.URL.Query(), &params.AccountId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		return
	}

	// ------------- Optional query parameter "template_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "template_id", r.URL.Query(), &params.TemplateId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameter("form", true, false, "model", r.URL.Query(), &params.Model)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserTempBalances operation middleware
func (siw *ServerInterfaceWrapper) GetUserTempBalances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserTempBalances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserUsageLogs operation middleware
func (siw *ServerInterfaceWrapper) GetUserUsageLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserUsageLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "key_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "key_id", r.URL.Query(), &params.KeyId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameter("form", true, false, "model", r.URL.Query(), &params.Model)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", r.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	// ------------- Optional query parameter "error_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_type", r.URL.Query(), &params.ErrorType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_type", Err: err})
		return
	}

	// ------------- Required query parameter "from" -------------

	if paramValue := r.URL.Query().Get("from"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := r.URL.Query().Get("to"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserUsageLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/auth/change-password", wrapper.PostUserAuthChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/auth/login", wrapper.PostUserAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/auth/me", wrapper.GetUserAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/auth/register", wrapper.PostUserAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/err_logs", wrapper.GetUserErrLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/groups", wrapper.GetUserGroups)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/keys", wrapper.GetUserKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/keys", wrapper.PostUserKeys)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/user/keys/{id}", wrapper.DeleteUserKeysId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/keys/{id}", wrapper.GetUserKeysId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/user/keys/{id}", wrapper.PutUserKeysId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/keys/{id}/rotate", wrapper.PostUserKeysIdRotate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/redemptions", wrapper.GetUserRedemptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/redemptions", wrapper.PostUserRedemptions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/stats", wrapper.GetUserStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/temp-balances", wrapper.GetUserTempBalances)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/usage_logs", wrapper.GetUserUsageLogs)
	})

	return r
}
