// Code generated by ent, DO NOT EDIT.

package emailcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldEmail, v))
}

// CodeSha256 applies equality check predicate on the "code_sha256" field. It's identical to CodeSha256EQ.
func CodeSha256(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldCodeSha256, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldExpiresAt, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldAttempts, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldContainsFold(FieldEmail, v))
}

// PurposeEQ applies the EQ predicate on the "purpose" field.
func PurposeEQ(v Purpose) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldPurpose, v))
}

// PurposeNEQ applies the NEQ predicate on the "purpose" field.
func PurposeNEQ(v Purpose) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldPurpose, v))
}

// PurposeIn applies the In predicate on the "purpose" field.
func PurposeIn(vs ...Purpose) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldPurpose, vs...))
}

// PurposeNotIn applies the NotIn predicate on the "purpose" field.
func PurposeNotIn(vs ...Purpose) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldPurpose, vs...))
}

// CodeSha256EQ applies the EQ predicate on the "code_sha256" field.
func CodeSha256EQ(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldCodeSha256, v))
}

// CodeSha256NEQ applies the NEQ predicate on the "code_sha256" field.
func CodeSha256NEQ(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldCodeSha256, v))
}

// CodeSha256In applies the In predicate on the "code_sha256" field.
func CodeSha256In(vs ...string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldCodeSha256, vs...))
}

// CodeSha256NotIn applies the NotIn predicate on the "code_sha256" field.
func CodeSha256NotIn(vs ...string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldCodeSha256, vs...))
}

// CodeSha256GT applies the GT predicate on the "code_sha256" field.
func CodeSha256GT(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldCodeSha256, v))
}

// CodeSha256GTE applies the GTE predicate on the "code_sha256" field.
func CodeSha256GTE(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldCodeSha256, v))
}

// CodeSha256LT applies the LT predicate on the "code_sha256" field.
func CodeSha256LT(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldCodeSha256, v))
}

// CodeSha256LTE applies the LTE predicate on the "code_sha256" field.
func CodeSha256LTE(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldCodeSha256, v))
}

// CodeSha256Contains applies the Contains predicate on the "code_sha256" field.
func CodeSha256Contains(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldContains(FieldCodeSha256, v))
}

// CodeSha256HasPrefix applies the HasPrefix predicate on the "code_sha256" field.
func CodeSha256HasPrefix(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldHasPrefix(FieldCodeSha256, v))
}

// CodeSha256HasSuffix applies the HasSuffix predicate on the "code_sha256" field.
func CodeSha256HasSuffix(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldHasSuffix(FieldCodeSha256, v))
}

// CodeSha256EqualFold applies the EqualFold predicate on the "code_sha256" field.
func CodeSha256EqualFold(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEqualFold(FieldCodeSha256, v))
}

// CodeSha256ContainsFold applies the ContainsFold predicate on the "code_sha256" field.
func CodeSha256ContainsFold(v string) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldContainsFold(FieldCodeSha256, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldExpiresAt, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldAttempts, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailCode {
	return predicate.EmailCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailCode) predicate.EmailCode {
	return predicate.EmailCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailCode) predicate.EmailCode {
	return predicate.EmailCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailCode) predicate.EmailCode {
	return predicate.EmailCode(sql.NotPredicates(p))
}
