// Code generated by ent, DO NOT EDIT.

package supplierreconciliation

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the supplierreconciliation type in the database.
	Label = "supplier_reconciliation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSupplierUserID holds the string denoting the supplier_user_id field in the database.
	FieldSupplierUserID = "supplier_user_id"
	// FieldSourceDay holds the string denoting the source_day field in the database.
	FieldSourceDay = "source_day"
	// FieldGrossCost holds the string denoting the gross_cost field in the database.
	FieldGrossCost = "gross_cost"
	// FieldEarned holds the string denoting the earned field in the database.
	FieldEarned = "earned"
	// FieldRowCount holds the string denoting the row_count field in the database.
	FieldRowCount = "row_count"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldClosedRevision holds the string denoting the closed_revision field in the database.
	FieldClosedRevision = "closed_revision"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// Table holds the table name of the supplierreconciliation in the database.
	Table = "supplier_reconciliation"
)

// Columns holds all SQL columns for supplierreconciliation fields.
var Columns = []string{
	FieldID,
	FieldSupplierUserID,
	FieldSourceDay,
	FieldGrossCost,
	FieldEarned,
	FieldRowCount,
	FieldState,
	FieldClosedRevision,
	FieldClosedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGrossCost holds the default value on creation for the "gross_cost" field.
	DefaultGrossCost int64
	// DefaultEarned holds the default value on creation for the "earned" field.
	DefaultEarned int64
	// DefaultRowCount holds the default value on creation for the "row_count" field.
	DefaultRowCount int64
)

// State defines the type for the "state" enum field.
type State string

// StateOpen is the default value of the State enum.
const DefaultState = StateOpen

// State values.
const (
	StateOpen   State = "open"
	StateClosed State = "closed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateOpen, StateClosed:
		return nil
	default:
		return fmt.Errorf("supplierreconciliation: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the SupplierReconciliation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySupplierUserID orders the results by the supplier_user_id field.
func BySupplierUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupplierUserID, opts...).ToFunc()
}

// BySourceDay orders the results by the source_day field.
func BySourceDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceDay, opts...).ToFunc()
}

// ByGrossCost orders the results by the gross_cost field.
func ByGrossCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrossCost, opts...).ToFunc()
}

// ByEarned orders the results by the earned field.
func ByEarned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEarned, opts...).ToFunc()
}

// ByRowCount orders the results by the row_count field.
func ByRowCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowCount, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByClosedRevision orders the results by the closed_revision field.
func ByClosedRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedRevision, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}
