// Code generated by ent, DO NOT EDIT.

package supplierfrozenchunk

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the supplierfrozenchunk type in the database.
	Label = "supplier_frozen_chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSupplierUserID holds the string denoting the supplier_user_id field in the database.
	FieldSupplierUserID = "supplier_user_id"
	// FieldAvailableAt holds the string denoting the available_at field in the database.
	FieldAvailableAt = "available_at"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// Table holds the table name of the supplierfrozenchunk in the database.
	Table = "supplier_frozen_chunks"
)

// Columns holds all SQL columns for supplierfrozenchunk fields.
var Columns = []string{
	FieldID,
	FieldSupplierUserID,
	FieldAvailableAt,
	FieldAmount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SupplierFrozenChunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySupplierUserID orders the results by the supplier_user_id field.
func BySupplierUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupplierUserID, opts...).ToFunc()
}

// ByAvailableAt orders the results by the available_at field.
func ByAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAt, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}
